// Code generated by nex-gen. DO NOT EDIT.
package workflow

import (
	"time"

	enums "go.temporal.io/api/enums/v1"
	sdk "go.temporal.io/api/sdk/v1"
	workflowservice "go.temporal.io/api/workflowservice/v1"
	"go.temporal.io/sdk/client"
	"go.temporal.io/sdk/temporal"
)

const ServiceName = "temporal.api.workflowservice.v1.WorkflowService"
const Endpoint = "__temporal_system"

const SignalWithStartWorkflowOp = "SignalWithStartWorkflowExecution"

// --- Datatypes ---

type SignalWithStartWorkflowRequest struct {
	// Required.
	Workflow string
	// Arguments for the workflow.
	Args []any
	// Required. Unique identifier for the workflow execution.
	Id string
	// Required. Task queue to run the workflow on.
	TaskQueue string
	// Required.
	Signal string
	// Arguments for the signal.
	SignalArgs []any
	// Total workflow execution timeout, including retries and continue-as-new.
	ExecutionTimeout *time.Duration
	// Timeout of a single workflow run.
	RunTimeout *time.Duration
	// Timeout of a single workflow task.
	TaskTimeout *time.Duration
	// Request ID used to deduplicate workflow start requests.
	RequestId *string
	// Behavior when a closed workflow with the same ID exists. Default is allow-duplicate.
	IdReusePolicy *enums.WorkflowIdReusePolicy
	// Behavior when a workflow is currently running with the same ID. Set to use-existing
	// for idempotent deduplication on workflow ID. Cannot be set if id-reuse-policy is
	// terminate-if-running.
	IdConflictPolicy *enums.WorkflowIdConflictPolicy
	// Retry policy for the workflow.
	RetryPolicy *temporal.RetryPolicy
	// Cron schedule for recurring workflow executions. See
	// https://docs.temporal.io/cron-job.
	CronSchedule *string
	// Memo for the workflow.
	Memo map[string]any
	// Typed search attributes for the workflow.
	SearchAttributes *string
	// Priority of the workflow execution.
	Priority *temporal.Priority
	// Override for workflow versioning behavior.
	VersioningOverride *client.VersioningOverride
	// Amount of time to wait before starting the workflow. This does not work with
	// cron-schedule.
	StartDelay   *time.Duration
	UserMetadata *UserMetadata
}

func (m SignalWithStartWorkflowRequest) ToProto() *workflowservice.SignalWithStartWorkflowExecutionRequest {
	message := &workflowservice.SignalWithStartWorkflowExecutionRequest{}
	message.WorkflowType = WorkflowTypeToProto(&m.Workflow)
	message.Input = PayloadsToProto(m.Args)
	message.WorkflowId = m.Id
	message.TaskQueue = TaskQueueToProto(&m.TaskQueue)
	message.SignalName = m.Signal
	message.SignalInput = PayloadsToProto(m.SignalArgs)
	message.WorkflowExecutionTimeout = DurationToProto(m.ExecutionTimeout)
	message.WorkflowRunTimeout = DurationToProto(m.RunTimeout)
	message.WorkflowTaskTimeout = DurationToProto(m.TaskTimeout)
	if m.RequestId != nil {
		message.RequestId = (*m.RequestId)
	}
	if m.IdReusePolicy != nil {
		message.WorkflowIdReusePolicy = enums.WorkflowIdReusePolicy((*m.IdReusePolicy))
	}
	if m.IdConflictPolicy != nil {
		message.WorkflowIdConflictPolicy = enums.WorkflowIdConflictPolicy((*m.IdConflictPolicy))
	}
	message.RetryPolicy = RetryPolicyToProto(m.RetryPolicy)
	if m.CronSchedule != nil {
		message.CronSchedule = (*m.CronSchedule)
	}
	message.Memo = MemoToProto(m.Memo)
	message.SearchAttributes = SearchAttributesToProto(m.SearchAttributes)
	message.Priority = PriorityToProto(m.Priority)
	message.VersioningOverride = VersioningOverrideToProto(m.VersioningOverride)
	message.WorkflowStartDelay = DurationToProto(m.StartDelay)
	if m.UserMetadata != nil {
		message.UserMetadata = (*m.UserMetadata).ToProto()
	}
	message.Namespace = WorkflowNamespace()
	return message
}

type UserMetadata struct {
	// Single-line fixed summary for the workflow execution that may appear in UI and CLI.
	// This can be in single-line Temporal Markdown format.
	StaticSummary any
	// General fixed details for the workflow execution that may appear in UI and CLI. This
	// can be in Temporal Markdown format and can span multiple lines. This value is fixed
	// on the workflow execution and cannot be updated.
	StaticDetails any
}

func (m UserMetadata) ToProto() *sdk.UserMetadata {
	message := &sdk.UserMetadata{}
	message.Summary = PayloadToProto(m.StaticSummary)
	message.Details = PayloadToProto(m.StaticDetails)
	return message
}

func UserMetadataFromProto(proto *sdk.UserMetadata) UserMetadata {
	value := UserMetadata{}
	value.StaticSummary = PayloadFromProto(proto.GetSummary())
	value.StaticDetails = PayloadFromProto(proto.GetDetails())
	return value
}

type SignalWithStartWorkflowResponse struct {
}

func (m SignalWithStartWorkflowResponse) ToProto() *workflowservice.SignalWithStartWorkflowExecutionResponse {
	message := &workflowservice.SignalWithStartWorkflowExecutionResponse{}
	return message
}

func SignalWithStartWorkflowResponseFromProto(proto *workflowservice.SignalWithStartWorkflowExecutionResponse) SignalWithStartWorkflowResponse {
	value := SignalWithStartWorkflowResponse{}
	return value
}

// --- Operations (internal) ---

func signalWithStartWorkflow(ctx Context, request SignalWithStartWorkflowRequest) (*SignalWithStartWorkflowResponse, error) {
	c := NewNexusClient(Endpoint, ServiceName)
	fut := c.ExecuteOperation(ctx, SignalWithStartWorkflowOp, request.ToProto(), NexusOperationOptions{})
	var result workflowservice.SignalWithStartWorkflowExecutionResponse
	if err := fut.Get(ctx, &result); err != nil {
		return nil, err
	}
	value := SignalWithStartWorkflowResponseFromProto(&result)
	return &value, nil
}

// --- Operations (public API) ---

type SignalWithStartWorkflowOptions struct {
	// Arguments for the workflow.
	Args []any
	// Arguments for the signal.
	SignalArgs []any
	// Total workflow execution timeout, including retries and continue-as-new.
	ExecutionTimeout *time.Duration
	// Timeout of a single workflow run.
	RunTimeout *time.Duration
	// Timeout of a single workflow task.
	TaskTimeout *time.Duration
	// Request ID used to deduplicate workflow start requests.
	RequestId *string
	// Behavior when a closed workflow with the same ID exists. Default is allow-duplicate.
	IdReusePolicy *enums.WorkflowIdReusePolicy
	// Behavior when a workflow is currently running with the same ID. Set to use-existing
	// for idempotent deduplication on workflow ID. Cannot be set if id-reuse-policy is
	// terminate-if-running.
	IdConflictPolicy *enums.WorkflowIdConflictPolicy
	// Retry policy for the workflow.
	RetryPolicy *temporal.RetryPolicy
	// Cron schedule for recurring workflow executions. See
	// https://docs.temporal.io/cron-job.
	CronSchedule *string
	// Memo for the workflow.
	Memo map[string]any
	// Typed search attributes for the workflow.
	SearchAttributes *string
	// Priority of the workflow execution.
	Priority *temporal.Priority
	// Override for workflow versioning behavior.
	VersioningOverride *client.VersioningOverride
	// Amount of time to wait before starting the workflow. This does not work with
	// cron-schedule.
	StartDelay *time.Duration
	UserMetadata
}

// Signal a workflow, starting it first if needed.
//
// Returns: A workflow handle to the started workflow.
func SignalWithStartWorkflow(
	ctx Context,
	workflow string,
	id string,
	taskQueue string,
	signal string,
	opts SignalWithStartWorkflowOptions,
) (*SignalWithStartWorkflowResponse, error) {
	return signalWithStartWorkflow(ctx, SignalWithStartWorkflowRequest{
		Workflow:           workflow,
		Args:               opts.Args,
		Id:                 id,
		TaskQueue:          taskQueue,
		Signal:             signal,
		SignalArgs:         opts.SignalArgs,
		ExecutionTimeout:   opts.ExecutionTimeout,
		RunTimeout:         opts.RunTimeout,
		TaskTimeout:        opts.TaskTimeout,
		RequestId:          opts.RequestId,
		IdReusePolicy:      opts.IdReusePolicy,
		IdConflictPolicy:   opts.IdConflictPolicy,
		RetryPolicy:        opts.RetryPolicy,
		CronSchedule:       opts.CronSchedule,
		Memo:               opts.Memo,
		SearchAttributes:   opts.SearchAttributes,
		Priority:           opts.Priority,
		VersioningOverride: opts.VersioningOverride,
		StartDelay:         opts.StartDelay,
		UserMetadata:       &opts.UserMetadata,
	})
}
