// Code generated by nex-gen. DO NOT EDIT.
package workflow

import (
	"time"

	enums "go.temporal.io/api/enums/v1"
	sdk "go.temporal.io/api/sdk/v1"
	workflowservice "go.temporal.io/api/workflowservice/v1"
	"go.temporal.io/sdk/client"
	"go.temporal.io/sdk/temporal"
)

// --- Datatypes ---

type signalWithStartWorkflowRequest struct {
	// Required.
	Workflow string
	// Arguments for the workflow.
	Args []any
	// Required. Unique identifier for the workflow execution.
	Id string
	// Required. Task queue to run the workflow on.
	TaskQueue string
	// Required.
	Signal string
	// Arguments for the signal.
	SignalArgs []any
	// Total workflow execution timeout, including retries and continue-as-new.
	ExecutionTimeout *time.Duration
	// Timeout of a single workflow run.
	RunTimeout *time.Duration
	// Timeout of a single workflow task.
	TaskTimeout *time.Duration
	// Request ID used to deduplicate workflow start requests.
	RequestId *string
	// Behavior when a closed workflow with the same ID exists. Default is allow-duplicate.
	IdReusePolicy *enums.WorkflowIdReusePolicy
	// Behavior when a workflow is currently running with the same ID. Set to use-existing
	// for idempotent deduplication on workflow ID. Cannot be set if id-reuse-policy is
	// terminate-if-running.
	IdConflictPolicy *enums.WorkflowIdConflictPolicy
	// Retry policy for the workflow.
	RetryPolicy *temporal.RetryPolicy
	// Cron schedule for recurring workflow executions. See
	// https://docs.temporal.io/cron-job.
	CronSchedule *string
	// Memo for the workflow.
	Memo map[string]any
	// Typed search attributes for the workflow.
	SearchAttributes temporal.SearchAttributes
	// Priority of the workflow execution.
	Priority *temporal.Priority
	// Override for workflow versioning behavior.
	VersioningOverride client.VersioningOverride
	// Amount of time to wait before starting the workflow. This does not work with
	// cron-schedule.
	StartDelay   *time.Duration
	UserMetadata *UserMetadata
}

func (m signalWithStartWorkflowRequest) toProto(ctx Context) (*workflowservice.SignalWithStartWorkflowExecutionRequest, error) {
	message := &workflowservice.SignalWithStartWorkflowExecutionRequest{}
	{
		converted, err := workflowTypeToProto(ctx, &m.Workflow)
		if err != nil {
			return nil, err
		}
		message.WorkflowType = converted
	}
	{
		converted, err := payloadsToProto(ctx, m.Args)
		if err != nil {
			return nil, err
		}
		message.Input = converted
	}
	message.WorkflowId = m.Id
	{
		converted, err := taskQueueToProto(ctx, &m.TaskQueue)
		if err != nil {
			return nil, err
		}
		message.TaskQueue = converted
	}
	message.SignalName = m.Signal
	{
		converted, err := payloadsToProto(ctx, m.SignalArgs)
		if err != nil {
			return nil, err
		}
		message.SignalInput = converted
	}
	{
		converted, err := durationToProto(ctx, m.ExecutionTimeout)
		if err != nil {
			return nil, err
		}
		message.WorkflowExecutionTimeout = converted
	}
	{
		converted, err := durationToProto(ctx, m.RunTimeout)
		if err != nil {
			return nil, err
		}
		message.WorkflowRunTimeout = converted
	}
	{
		converted, err := durationToProto(ctx, m.TaskTimeout)
		if err != nil {
			return nil, err
		}
		message.WorkflowTaskTimeout = converted
	}
	if m.RequestId != nil {
		message.RequestId = (*m.RequestId)
	}
	if m.IdReusePolicy != nil {
		message.WorkflowIdReusePolicy = enums.WorkflowIdReusePolicy((*m.IdReusePolicy))
	}
	if m.IdConflictPolicy != nil {
		message.WorkflowIdConflictPolicy = enums.WorkflowIdConflictPolicy((*m.IdConflictPolicy))
	}
	{
		converted, err := retryPolicyToProto(ctx, m.RetryPolicy)
		if err != nil {
			return nil, err
		}
		message.RetryPolicy = converted
	}
	if m.CronSchedule != nil {
		message.CronSchedule = (*m.CronSchedule)
	}
	{
		converted, err := memoToProto(ctx, m.Memo)
		if err != nil {
			return nil, err
		}
		message.Memo = converted
	}
	{
		converted, err := searchAttributesToProto(ctx, &m.SearchAttributes)
		if err != nil {
			return nil, err
		}
		message.SearchAttributes = converted
	}
	{
		converted, err := priorityToProto(ctx, m.Priority)
		if err != nil {
			return nil, err
		}
		message.Priority = converted
	}
	{
		converted, err := versioningOverrideToProto(ctx, &m.VersioningOverride)
		if err != nil {
			return nil, err
		}
		message.VersioningOverride = converted
	}
	{
		converted, err := durationToProto(ctx, m.StartDelay)
		if err != nil {
			return nil, err
		}
		message.WorkflowStartDelay = converted
	}
	if m.UserMetadata != nil {
		converted, err := (*m.UserMetadata).toProto(ctx)
		if err != nil {
			return nil, err
		}
		message.UserMetadata = converted
	}
	message.Namespace = workflowNamespace()
	return message, nil
}

// --- Operations (internal) ---

func signalWithStartWorkflow(ctx Context, request signalWithStartWorkflowRequest) (*SignalWithStartWorkflowResponse, error) {
	requestProto, err := request.toProto(ctx)
	if err != nil {
		return nil, err
	}
	c := NewNexusClient("__temporal_system", "temporal.api.workflowservice.v1.WorkflowService")
	fut := c.ExecuteOperation(ctx, "SignalWithStartWorkflowExecution", requestProto, NexusOperationOptions{})
	var result workflowservice.SignalWithStartWorkflowExecutionResponse
	if err := fut.Get(ctx, &result); err != nil {
		return nil, err
	}
	value, err := signalWithStartWorkflowResponseFromProto(ctx, &result)
	if err != nil {
		return nil, err
	}
	return &value, nil
}

// --- Operations (public API) ---

type UserMetadata struct {
	// Single-line fixed summary for the workflow execution that may appear in UI and CLI.
	// This can be in single-line Temporal Markdown format.
	StaticSummary any
	// General fixed details for the workflow execution that may appear in UI and CLI. This
	// can be in Temporal Markdown format and can span multiple lines. This value is fixed
	// on the workflow execution and cannot be updated.
	StaticDetails any
}

func (m UserMetadata) toProto(ctx Context) (*sdk.UserMetadata, error) {
	message := &sdk.UserMetadata{}
	{
		converted, err := payloadToProto(ctx, m.StaticSummary)
		if err != nil {
			return nil, err
		}
		message.Summary = converted
	}
	{
		converted, err := payloadToProto(ctx, m.StaticDetails)
		if err != nil {
			return nil, err
		}
		message.Details = converted
	}
	return message, nil
}

func userMetadataFromProto(ctx Context, proto *sdk.UserMetadata) (UserMetadata, error) {
	value := UserMetadata{}
	{
		converted, err := payloadFromProto(ctx, proto.GetSummary())
		if err != nil {
			return value, err
		}
		value.StaticSummary = converted
	}
	{
		converted, err := payloadFromProto(ctx, proto.GetDetails())
		if err != nil {
			return value, err
		}
		value.StaticDetails = converted
	}
	return value, nil
}

type SignalWithStartWorkflowResponse struct {
}

func (m SignalWithStartWorkflowResponse) toProto(ctx Context) (*workflowservice.SignalWithStartWorkflowExecutionResponse, error) {
	message := &workflowservice.SignalWithStartWorkflowExecutionResponse{}
	return message, nil
}

func signalWithStartWorkflowResponseFromProto(ctx Context, proto *workflowservice.SignalWithStartWorkflowExecutionResponse) (SignalWithStartWorkflowResponse, error) {
	value := SignalWithStartWorkflowResponse{}
	return value, nil
}

type SignalWithStartWorkflowOptions struct {
	// Arguments for the workflow.
	Args []any
	// Arguments for the signal.
	SignalArgs []any
	// Total workflow execution timeout, including retries and continue-as-new.
	ExecutionTimeout *time.Duration
	// Timeout of a single workflow run.
	RunTimeout *time.Duration
	// Timeout of a single workflow task.
	TaskTimeout *time.Duration
	// Request ID used to deduplicate workflow start requests.
	RequestId *string
	// Behavior when a closed workflow with the same ID exists. Default is allow-duplicate.
	IdReusePolicy *enums.WorkflowIdReusePolicy
	// Behavior when a workflow is currently running with the same ID. Set to use-existing
	// for idempotent deduplication on workflow ID. Cannot be set if id-reuse-policy is
	// terminate-if-running.
	IdConflictPolicy *enums.WorkflowIdConflictPolicy
	// Retry policy for the workflow.
	RetryPolicy *temporal.RetryPolicy
	// Cron schedule for recurring workflow executions. See
	// https://docs.temporal.io/cron-job.
	CronSchedule *string
	// Memo for the workflow.
	Memo map[string]any
	// Typed search attributes for the workflow.
	SearchAttributes temporal.SearchAttributes
	// Priority of the workflow execution.
	Priority *temporal.Priority
	// Override for workflow versioning behavior.
	VersioningOverride client.VersioningOverride
	// Amount of time to wait before starting the workflow. This does not work with
	// cron-schedule.
	StartDelay *time.Duration
	UserMetadata
}

// Signal a workflow, starting it first if needed.
//
// Returns: A workflow handle to the started workflow.
func SignalWithStartWorkflow(
	ctx Context,
	workflow string,
	id string,
	taskQueue string,
	signal string,
	opts SignalWithStartWorkflowOptions,
) (*SignalWithStartWorkflowResponse, error) {
	return signalWithStartWorkflow(ctx, signalWithStartWorkflowRequest{
		Workflow:           workflow,
		Args:               opts.Args,
		Id:                 id,
		TaskQueue:          taskQueue,
		Signal:             signal,
		SignalArgs:         opts.SignalArgs,
		ExecutionTimeout:   opts.ExecutionTimeout,
		RunTimeout:         opts.RunTimeout,
		TaskTimeout:        opts.TaskTimeout,
		RequestId:          opts.RequestId,
		IdReusePolicy:      opts.IdReusePolicy,
		IdConflictPolicy:   opts.IdConflictPolicy,
		RetryPolicy:        opts.RetryPolicy,
		CronSchedule:       opts.CronSchedule,
		Memo:               opts.Memo,
		SearchAttributes:   opts.SearchAttributes,
		Priority:           opts.Priority,
		VersioningOverride: opts.VersioningOverride,
		StartDelay:         opts.StartDelay,
		UserMetadata:       &opts.UserMetadata,
	})
}
