version: "3.5"

services:
  cassandra:
    image: cassandra:3.11
    ports:
      - "9042:9042"
    networks:
      services-network:
        aliases:
          - cassandra

  temporal:
    image: temporaliotest/auto-setup:latest
    ports:
      - "7233:7233"
      - "7234:7234"
      - "7235:7235"
      - "7239:7239"
    environment:
      - "CASSANDRA_SEEDS=cassandra"
      - "DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development.yaml"
    depends_on:
      - cassandra
    networks:
      services-network:
        aliases:
          - temporal

  build:
    build:
      context: ../
      dockerfile: ./.buildkite/Dockerfile
    environment:
      - "GO111MODULE=on"
    volumes:
      - ../:/go/src/go.temporal.io/sdk
    networks:
      services-network:
        aliases:
          - build

  integ-test:
    build:
      context: ../
      dockerfile: ./.buildkite/Dockerfile
    environment:
      - "SERVICE_ADDR=temporal:7233"
      - "GO111MODULE=on"
    depends_on:
      - temporal
    volumes:
      - ../:/go/src/go.temporal.io/sdk
    networks:
      services-network:
        aliases:
          - integ-test

  unit-test:
    build:
      context: ../
      dockerfile: ./.buildkite/Dockerfile
    environment:
      - "GO111MODULE=on"
    volumes:
      - ../:/go/src/go.temporal.io/sdk
    networks:
      services-network:
        aliases:
          - unit-test

  coverage-report:
    build:
      context: ../
      dockerfile: ./.buildkite/Dockerfile
    environment:
      - CI
      - BUILDKITE
      - BUILDKITE_AGENT_ACCESS_TOKEN
      - BUILDKITE_JOB_ID
      - BUILDKITE_BUILD_ID
      - BUILDKITE_BUILD_NUMBER
      - BUILDKITE_BRANCH
      - BUILDKITE_BUILD_URL
      - BUILDKITE_PROJECT_SLUG
      - BUILDKITE_COMMIT
      - BUILDKITE_PULL_REQUEST
      - BUILDKITE_TAG
      - BUILDKITE_REPO
      - BUILDKITE_BUILD_CREATOR
      - BUILDKITE_BUILD_CREATOR_EMAIL
      - BUILDKITE_BUILD_CREATOR_TEAMS
      - BUILDKITE_PULL_REQUEST_REPO
      - COVERALLS_TOKEN
      - "GO111MODULE=on"
    volumes:
      - ../:/go/src/go.temporal.io/sdk
      - /usr/bin/buildkite-agent:/usr/bin/buildkite-agent

  fossa:
    build:
      context: ../
      dockerfile: ./.buildkite/Dockerfile
    environment:
      - "GO111MODULE=on"
      - BUILDKITE_BRANCH
      - FOSSA_API_KEY
    volumes:
      - ../:/go/src/go.temporal.io/sdk

networks:
  services-network:
    name: services-network
    driver: bridge
