steps:
  - label: ":golang: unit-test"
    agents:
      queue: "default"
      docker: "*"
    command: "make unit-test"
    artifact_paths:
      - ".build/coverage/*.out"
    plugins:
      - docker-compose#v3.1.0:
          run: unit-test
          config: docker/buildkite/docker-compose.yml

  - label: ":golang: integration-test-sticky-off"
    agents:
      queue: "default"
      docker: "*"
    command: "make integ_test_sticky_off"
    artifact_paths:
      - ".build/coverage/*.out"
    retry:
      automatic:
        limit: 1
    plugins:
      - docker-compose#v3.1.0:
          run: integ-test
          config: docker/buildkite/docker-compose.yml

  - label: ":golang: integration-test-sticky-on"
    agents:
      queue: "default"
      docker: "*"
    command: "make integration-test-sticky-on"
    artifact_paths:
      - ".build/coverage/*.out"
    retry:
      automatic:
        limit: 1
    plugins:
      - docker-compose#v3.1.0:
          run: integ-test
          config: docker/buildkite/docker-compose.yml

  - wait

  - label: ":golang: code-coverage"
    agents:
      queue: "default"
      docker: "*"
    command: ".buildkite/scripts/gocov.sh"
    plugins:
      - docker-compose#v3.1.0:
          run: coverage-report
          config: docker/buildkite/docker-compose.yml
