// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"go.temporal.io/sdk/converter"
	"go.temporal.io/sdk/internal"
)

// NewClientOutboundInterceptor creates a new instance of ClientOutboundInterceptor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClientOutboundInterceptor(t interface {
	mock.TestingT
	Cleanup(func())
}) *ClientOutboundInterceptor {
	mock := &ClientOutboundInterceptor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ClientOutboundInterceptor is an autogenerated mock type for the ClientOutboundInterceptor type
type ClientOutboundInterceptor struct {
	mock.Mock
}

type ClientOutboundInterceptor_Expecter struct {
	mock *mock.Mock
}

func (_m *ClientOutboundInterceptor) EXPECT() *ClientOutboundInterceptor_Expecter {
	return &ClientOutboundInterceptor_Expecter{mock: &_m.Mock}
}

// CancelWorkflow provides a mock function for the type ClientOutboundInterceptor
func (_mock *ClientOutboundInterceptor) CancelWorkflow(context1 context.Context, clientCancelWorkflowInput *internal.ClientCancelWorkflowInput) error {
	ret := _mock.Called(context1, clientCancelWorkflowInput)

	if len(ret) == 0 {
		panic("no return value specified for CancelWorkflow")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *internal.ClientCancelWorkflowInput) error); ok {
		r0 = returnFunc(context1, clientCancelWorkflowInput)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ClientOutboundInterceptor_CancelWorkflow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelWorkflow'
type ClientOutboundInterceptor_CancelWorkflow_Call struct {
	*mock.Call
}

// CancelWorkflow is a helper method to define mock.On call
//   - context1 context.Context
//   - clientCancelWorkflowInput *internal.ClientCancelWorkflowInput
func (_e *ClientOutboundInterceptor_Expecter) CancelWorkflow(context1 interface{}, clientCancelWorkflowInput interface{}) *ClientOutboundInterceptor_CancelWorkflow_Call {
	return &ClientOutboundInterceptor_CancelWorkflow_Call{Call: _e.mock.On("CancelWorkflow", context1, clientCancelWorkflowInput)}
}

func (_c *ClientOutboundInterceptor_CancelWorkflow_Call) Run(run func(context1 context.Context, clientCancelWorkflowInput *internal.ClientCancelWorkflowInput)) *ClientOutboundInterceptor_CancelWorkflow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *internal.ClientCancelWorkflowInput
		if args[1] != nil {
			arg1 = args[1].(*internal.ClientCancelWorkflowInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ClientOutboundInterceptor_CancelWorkflow_Call) Return(err error) *ClientOutboundInterceptor_CancelWorkflow_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ClientOutboundInterceptor_CancelWorkflow_Call) RunAndReturn(run func(context1 context.Context, clientCancelWorkflowInput *internal.ClientCancelWorkflowInput) error) *ClientOutboundInterceptor_CancelWorkflow_Call {
	_c.Call.Return(run)
	return _c
}

// CreateSchedule provides a mock function for the type ClientOutboundInterceptor
func (_mock *ClientOutboundInterceptor) CreateSchedule(ctx context.Context, options *internal.ScheduleClientCreateInput) (internal.ScheduleHandle, error) {
	ret := _mock.Called(ctx, options)

	if len(ret) == 0 {
		panic("no return value specified for CreateSchedule")
	}

	var r0 internal.ScheduleHandle
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *internal.ScheduleClientCreateInput) (internal.ScheduleHandle, error)); ok {
		return returnFunc(ctx, options)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *internal.ScheduleClientCreateInput) internal.ScheduleHandle); ok {
		r0 = returnFunc(ctx, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(internal.ScheduleHandle)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *internal.ScheduleClientCreateInput) error); ok {
		r1 = returnFunc(ctx, options)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ClientOutboundInterceptor_CreateSchedule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSchedule'
type ClientOutboundInterceptor_CreateSchedule_Call struct {
	*mock.Call
}

// CreateSchedule is a helper method to define mock.On call
//   - ctx context.Context
//   - options *internal.ScheduleClientCreateInput
func (_e *ClientOutboundInterceptor_Expecter) CreateSchedule(ctx interface{}, options interface{}) *ClientOutboundInterceptor_CreateSchedule_Call {
	return &ClientOutboundInterceptor_CreateSchedule_Call{Call: _e.mock.On("CreateSchedule", ctx, options)}
}

func (_c *ClientOutboundInterceptor_CreateSchedule_Call) Run(run func(ctx context.Context, options *internal.ScheduleClientCreateInput)) *ClientOutboundInterceptor_CreateSchedule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *internal.ScheduleClientCreateInput
		if args[1] != nil {
			arg1 = args[1].(*internal.ScheduleClientCreateInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ClientOutboundInterceptor_CreateSchedule_Call) Return(scheduleHandle internal.ScheduleHandle, err error) *ClientOutboundInterceptor_CreateSchedule_Call {
	_c.Call.Return(scheduleHandle, err)
	return _c
}

func (_c *ClientOutboundInterceptor_CreateSchedule_Call) RunAndReturn(run func(ctx context.Context, options *internal.ScheduleClientCreateInput) (internal.ScheduleHandle, error)) *ClientOutboundInterceptor_CreateSchedule_Call {
	_c.Call.Return(run)
	return _c
}

// DescribeWorkflow provides a mock function for the type ClientOutboundInterceptor
func (_mock *ClientOutboundInterceptor) DescribeWorkflow(context1 context.Context, clientDescribeWorkflowInput *internal.ClientDescribeWorkflowInput) (*internal.ClientDescribeWorkflowOutput, error) {
	ret := _mock.Called(context1, clientDescribeWorkflowInput)

	if len(ret) == 0 {
		panic("no return value specified for DescribeWorkflow")
	}

	var r0 *internal.ClientDescribeWorkflowOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *internal.ClientDescribeWorkflowInput) (*internal.ClientDescribeWorkflowOutput, error)); ok {
		return returnFunc(context1, clientDescribeWorkflowInput)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *internal.ClientDescribeWorkflowInput) *internal.ClientDescribeWorkflowOutput); ok {
		r0 = returnFunc(context1, clientDescribeWorkflowInput)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*internal.ClientDescribeWorkflowOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *internal.ClientDescribeWorkflowInput) error); ok {
		r1 = returnFunc(context1, clientDescribeWorkflowInput)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ClientOutboundInterceptor_DescribeWorkflow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DescribeWorkflow'
type ClientOutboundInterceptor_DescribeWorkflow_Call struct {
	*mock.Call
}

// DescribeWorkflow is a helper method to define mock.On call
//   - context1 context.Context
//   - clientDescribeWorkflowInput *internal.ClientDescribeWorkflowInput
func (_e *ClientOutboundInterceptor_Expecter) DescribeWorkflow(context1 interface{}, clientDescribeWorkflowInput interface{}) *ClientOutboundInterceptor_DescribeWorkflow_Call {
	return &ClientOutboundInterceptor_DescribeWorkflow_Call{Call: _e.mock.On("DescribeWorkflow", context1, clientDescribeWorkflowInput)}
}

func (_c *ClientOutboundInterceptor_DescribeWorkflow_Call) Run(run func(context1 context.Context, clientDescribeWorkflowInput *internal.ClientDescribeWorkflowInput)) *ClientOutboundInterceptor_DescribeWorkflow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *internal.ClientDescribeWorkflowInput
		if args[1] != nil {
			arg1 = args[1].(*internal.ClientDescribeWorkflowInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ClientOutboundInterceptor_DescribeWorkflow_Call) Return(clientDescribeWorkflowOutput *internal.ClientDescribeWorkflowOutput, err error) *ClientOutboundInterceptor_DescribeWorkflow_Call {
	_c.Call.Return(clientDescribeWorkflowOutput, err)
	return _c
}

func (_c *ClientOutboundInterceptor_DescribeWorkflow_Call) RunAndReturn(run func(context1 context.Context, clientDescribeWorkflowInput *internal.ClientDescribeWorkflowInput) (*internal.ClientDescribeWorkflowOutput, error)) *ClientOutboundInterceptor_DescribeWorkflow_Call {
	_c.Call.Return(run)
	return _c
}

// ExecuteWorkflow provides a mock function for the type ClientOutboundInterceptor
func (_mock *ClientOutboundInterceptor) ExecuteWorkflow(context1 context.Context, clientExecuteWorkflowInput *internal.ClientExecuteWorkflowInput) (internal.WorkflowRun, error) {
	ret := _mock.Called(context1, clientExecuteWorkflowInput)

	if len(ret) == 0 {
		panic("no return value specified for ExecuteWorkflow")
	}

	var r0 internal.WorkflowRun
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *internal.ClientExecuteWorkflowInput) (internal.WorkflowRun, error)); ok {
		return returnFunc(context1, clientExecuteWorkflowInput)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *internal.ClientExecuteWorkflowInput) internal.WorkflowRun); ok {
		r0 = returnFunc(context1, clientExecuteWorkflowInput)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(internal.WorkflowRun)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *internal.ClientExecuteWorkflowInput) error); ok {
		r1 = returnFunc(context1, clientExecuteWorkflowInput)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ClientOutboundInterceptor_ExecuteWorkflow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecuteWorkflow'
type ClientOutboundInterceptor_ExecuteWorkflow_Call struct {
	*mock.Call
}

// ExecuteWorkflow is a helper method to define mock.On call
//   - context1 context.Context
//   - clientExecuteWorkflowInput *internal.ClientExecuteWorkflowInput
func (_e *ClientOutboundInterceptor_Expecter) ExecuteWorkflow(context1 interface{}, clientExecuteWorkflowInput interface{}) *ClientOutboundInterceptor_ExecuteWorkflow_Call {
	return &ClientOutboundInterceptor_ExecuteWorkflow_Call{Call: _e.mock.On("ExecuteWorkflow", context1, clientExecuteWorkflowInput)}
}

func (_c *ClientOutboundInterceptor_ExecuteWorkflow_Call) Run(run func(context1 context.Context, clientExecuteWorkflowInput *internal.ClientExecuteWorkflowInput)) *ClientOutboundInterceptor_ExecuteWorkflow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *internal.ClientExecuteWorkflowInput
		if args[1] != nil {
			arg1 = args[1].(*internal.ClientExecuteWorkflowInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ClientOutboundInterceptor_ExecuteWorkflow_Call) Return(workflowRun internal.WorkflowRun, err error) *ClientOutboundInterceptor_ExecuteWorkflow_Call {
	_c.Call.Return(workflowRun, err)
	return _c
}

func (_c *ClientOutboundInterceptor_ExecuteWorkflow_Call) RunAndReturn(run func(context1 context.Context, clientExecuteWorkflowInput *internal.ClientExecuteWorkflowInput) (internal.WorkflowRun, error)) *ClientOutboundInterceptor_ExecuteWorkflow_Call {
	_c.Call.Return(run)
	return _c
}

// PollWorkflowUpdate provides a mock function for the type ClientOutboundInterceptor
func (_mock *ClientOutboundInterceptor) PollWorkflowUpdate(context1 context.Context, clientPollWorkflowUpdateInput *internal.ClientPollWorkflowUpdateInput) (*internal.ClientPollWorkflowUpdateOutput, error) {
	ret := _mock.Called(context1, clientPollWorkflowUpdateInput)

	if len(ret) == 0 {
		panic("no return value specified for PollWorkflowUpdate")
	}

	var r0 *internal.ClientPollWorkflowUpdateOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *internal.ClientPollWorkflowUpdateInput) (*internal.ClientPollWorkflowUpdateOutput, error)); ok {
		return returnFunc(context1, clientPollWorkflowUpdateInput)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *internal.ClientPollWorkflowUpdateInput) *internal.ClientPollWorkflowUpdateOutput); ok {
		r0 = returnFunc(context1, clientPollWorkflowUpdateInput)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*internal.ClientPollWorkflowUpdateOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *internal.ClientPollWorkflowUpdateInput) error); ok {
		r1 = returnFunc(context1, clientPollWorkflowUpdateInput)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ClientOutboundInterceptor_PollWorkflowUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PollWorkflowUpdate'
type ClientOutboundInterceptor_PollWorkflowUpdate_Call struct {
	*mock.Call
}

// PollWorkflowUpdate is a helper method to define mock.On call
//   - context1 context.Context
//   - clientPollWorkflowUpdateInput *internal.ClientPollWorkflowUpdateInput
func (_e *ClientOutboundInterceptor_Expecter) PollWorkflowUpdate(context1 interface{}, clientPollWorkflowUpdateInput interface{}) *ClientOutboundInterceptor_PollWorkflowUpdate_Call {
	return &ClientOutboundInterceptor_PollWorkflowUpdate_Call{Call: _e.mock.On("PollWorkflowUpdate", context1, clientPollWorkflowUpdateInput)}
}

func (_c *ClientOutboundInterceptor_PollWorkflowUpdate_Call) Run(run func(context1 context.Context, clientPollWorkflowUpdateInput *internal.ClientPollWorkflowUpdateInput)) *ClientOutboundInterceptor_PollWorkflowUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *internal.ClientPollWorkflowUpdateInput
		if args[1] != nil {
			arg1 = args[1].(*internal.ClientPollWorkflowUpdateInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ClientOutboundInterceptor_PollWorkflowUpdate_Call) Return(clientPollWorkflowUpdateOutput *internal.ClientPollWorkflowUpdateOutput, err error) *ClientOutboundInterceptor_PollWorkflowUpdate_Call {
	_c.Call.Return(clientPollWorkflowUpdateOutput, err)
	return _c
}

func (_c *ClientOutboundInterceptor_PollWorkflowUpdate_Call) RunAndReturn(run func(context1 context.Context, clientPollWorkflowUpdateInput *internal.ClientPollWorkflowUpdateInput) (*internal.ClientPollWorkflowUpdateOutput, error)) *ClientOutboundInterceptor_PollWorkflowUpdate_Call {
	_c.Call.Return(run)
	return _c
}

// QueryWorkflow provides a mock function for the type ClientOutboundInterceptor
func (_mock *ClientOutboundInterceptor) QueryWorkflow(context1 context.Context, clientQueryWorkflowInput *internal.ClientQueryWorkflowInput) (converter.EncodedValue, error) {
	ret := _mock.Called(context1, clientQueryWorkflowInput)

	if len(ret) == 0 {
		panic("no return value specified for QueryWorkflow")
	}

	var r0 converter.EncodedValue
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *internal.ClientQueryWorkflowInput) (converter.EncodedValue, error)); ok {
		return returnFunc(context1, clientQueryWorkflowInput)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *internal.ClientQueryWorkflowInput) converter.EncodedValue); ok {
		r0 = returnFunc(context1, clientQueryWorkflowInput)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(converter.EncodedValue)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *internal.ClientQueryWorkflowInput) error); ok {
		r1 = returnFunc(context1, clientQueryWorkflowInput)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ClientOutboundInterceptor_QueryWorkflow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryWorkflow'
type ClientOutboundInterceptor_QueryWorkflow_Call struct {
	*mock.Call
}

// QueryWorkflow is a helper method to define mock.On call
//   - context1 context.Context
//   - clientQueryWorkflowInput *internal.ClientQueryWorkflowInput
func (_e *ClientOutboundInterceptor_Expecter) QueryWorkflow(context1 interface{}, clientQueryWorkflowInput interface{}) *ClientOutboundInterceptor_QueryWorkflow_Call {
	return &ClientOutboundInterceptor_QueryWorkflow_Call{Call: _e.mock.On("QueryWorkflow", context1, clientQueryWorkflowInput)}
}

func (_c *ClientOutboundInterceptor_QueryWorkflow_Call) Run(run func(context1 context.Context, clientQueryWorkflowInput *internal.ClientQueryWorkflowInput)) *ClientOutboundInterceptor_QueryWorkflow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *internal.ClientQueryWorkflowInput
		if args[1] != nil {
			arg1 = args[1].(*internal.ClientQueryWorkflowInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ClientOutboundInterceptor_QueryWorkflow_Call) Return(encodedValue converter.EncodedValue, err error) *ClientOutboundInterceptor_QueryWorkflow_Call {
	_c.Call.Return(encodedValue, err)
	return _c
}

func (_c *ClientOutboundInterceptor_QueryWorkflow_Call) RunAndReturn(run func(context1 context.Context, clientQueryWorkflowInput *internal.ClientQueryWorkflowInput) (converter.EncodedValue, error)) *ClientOutboundInterceptor_QueryWorkflow_Call {
	_c.Call.Return(run)
	return _c
}

// SignalWithStartWorkflow provides a mock function for the type ClientOutboundInterceptor
func (_mock *ClientOutboundInterceptor) SignalWithStartWorkflow(context1 context.Context, clientSignalWithStartWorkflowInput *internal.ClientSignalWithStartWorkflowInput) (internal.WorkflowRun, error) {
	ret := _mock.Called(context1, clientSignalWithStartWorkflowInput)

	if len(ret) == 0 {
		panic("no return value specified for SignalWithStartWorkflow")
	}

	var r0 internal.WorkflowRun
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *internal.ClientSignalWithStartWorkflowInput) (internal.WorkflowRun, error)); ok {
		return returnFunc(context1, clientSignalWithStartWorkflowInput)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *internal.ClientSignalWithStartWorkflowInput) internal.WorkflowRun); ok {
		r0 = returnFunc(context1, clientSignalWithStartWorkflowInput)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(internal.WorkflowRun)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *internal.ClientSignalWithStartWorkflowInput) error); ok {
		r1 = returnFunc(context1, clientSignalWithStartWorkflowInput)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ClientOutboundInterceptor_SignalWithStartWorkflow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SignalWithStartWorkflow'
type ClientOutboundInterceptor_SignalWithStartWorkflow_Call struct {
	*mock.Call
}

// SignalWithStartWorkflow is a helper method to define mock.On call
//   - context1 context.Context
//   - clientSignalWithStartWorkflowInput *internal.ClientSignalWithStartWorkflowInput
func (_e *ClientOutboundInterceptor_Expecter) SignalWithStartWorkflow(context1 interface{}, clientSignalWithStartWorkflowInput interface{}) *ClientOutboundInterceptor_SignalWithStartWorkflow_Call {
	return &ClientOutboundInterceptor_SignalWithStartWorkflow_Call{Call: _e.mock.On("SignalWithStartWorkflow", context1, clientSignalWithStartWorkflowInput)}
}

func (_c *ClientOutboundInterceptor_SignalWithStartWorkflow_Call) Run(run func(context1 context.Context, clientSignalWithStartWorkflowInput *internal.ClientSignalWithStartWorkflowInput)) *ClientOutboundInterceptor_SignalWithStartWorkflow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *internal.ClientSignalWithStartWorkflowInput
		if args[1] != nil {
			arg1 = args[1].(*internal.ClientSignalWithStartWorkflowInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ClientOutboundInterceptor_SignalWithStartWorkflow_Call) Return(workflowRun internal.WorkflowRun, err error) *ClientOutboundInterceptor_SignalWithStartWorkflow_Call {
	_c.Call.Return(workflowRun, err)
	return _c
}

func (_c *ClientOutboundInterceptor_SignalWithStartWorkflow_Call) RunAndReturn(run func(context1 context.Context, clientSignalWithStartWorkflowInput *internal.ClientSignalWithStartWorkflowInput) (internal.WorkflowRun, error)) *ClientOutboundInterceptor_SignalWithStartWorkflow_Call {
	_c.Call.Return(run)
	return _c
}

// SignalWorkflow provides a mock function for the type ClientOutboundInterceptor
func (_mock *ClientOutboundInterceptor) SignalWorkflow(context1 context.Context, clientSignalWorkflowInput *internal.ClientSignalWorkflowInput) error {
	ret := _mock.Called(context1, clientSignalWorkflowInput)

	if len(ret) == 0 {
		panic("no return value specified for SignalWorkflow")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *internal.ClientSignalWorkflowInput) error); ok {
		r0 = returnFunc(context1, clientSignalWorkflowInput)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ClientOutboundInterceptor_SignalWorkflow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SignalWorkflow'
type ClientOutboundInterceptor_SignalWorkflow_Call struct {
	*mock.Call
}

// SignalWorkflow is a helper method to define mock.On call
//   - context1 context.Context
//   - clientSignalWorkflowInput *internal.ClientSignalWorkflowInput
func (_e *ClientOutboundInterceptor_Expecter) SignalWorkflow(context1 interface{}, clientSignalWorkflowInput interface{}) *ClientOutboundInterceptor_SignalWorkflow_Call {
	return &ClientOutboundInterceptor_SignalWorkflow_Call{Call: _e.mock.On("SignalWorkflow", context1, clientSignalWorkflowInput)}
}

func (_c *ClientOutboundInterceptor_SignalWorkflow_Call) Run(run func(context1 context.Context, clientSignalWorkflowInput *internal.ClientSignalWorkflowInput)) *ClientOutboundInterceptor_SignalWorkflow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *internal.ClientSignalWorkflowInput
		if args[1] != nil {
			arg1 = args[1].(*internal.ClientSignalWorkflowInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ClientOutboundInterceptor_SignalWorkflow_Call) Return(err error) *ClientOutboundInterceptor_SignalWorkflow_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ClientOutboundInterceptor_SignalWorkflow_Call) RunAndReturn(run func(context1 context.Context, clientSignalWorkflowInput *internal.ClientSignalWorkflowInput) error) *ClientOutboundInterceptor_SignalWorkflow_Call {
	_c.Call.Return(run)
	return _c
}

// TerminateWorkflow provides a mock function for the type ClientOutboundInterceptor
func (_mock *ClientOutboundInterceptor) TerminateWorkflow(context1 context.Context, clientTerminateWorkflowInput *internal.ClientTerminateWorkflowInput) error {
	ret := _mock.Called(context1, clientTerminateWorkflowInput)

	if len(ret) == 0 {
		panic("no return value specified for TerminateWorkflow")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *internal.ClientTerminateWorkflowInput) error); ok {
		r0 = returnFunc(context1, clientTerminateWorkflowInput)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ClientOutboundInterceptor_TerminateWorkflow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TerminateWorkflow'
type ClientOutboundInterceptor_TerminateWorkflow_Call struct {
	*mock.Call
}

// TerminateWorkflow is a helper method to define mock.On call
//   - context1 context.Context
//   - clientTerminateWorkflowInput *internal.ClientTerminateWorkflowInput
func (_e *ClientOutboundInterceptor_Expecter) TerminateWorkflow(context1 interface{}, clientTerminateWorkflowInput interface{}) *ClientOutboundInterceptor_TerminateWorkflow_Call {
	return &ClientOutboundInterceptor_TerminateWorkflow_Call{Call: _e.mock.On("TerminateWorkflow", context1, clientTerminateWorkflowInput)}
}

func (_c *ClientOutboundInterceptor_TerminateWorkflow_Call) Run(run func(context1 context.Context, clientTerminateWorkflowInput *internal.ClientTerminateWorkflowInput)) *ClientOutboundInterceptor_TerminateWorkflow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *internal.ClientTerminateWorkflowInput
		if args[1] != nil {
			arg1 = args[1].(*internal.ClientTerminateWorkflowInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ClientOutboundInterceptor_TerminateWorkflow_Call) Return(err error) *ClientOutboundInterceptor_TerminateWorkflow_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ClientOutboundInterceptor_TerminateWorkflow_Call) RunAndReturn(run func(context1 context.Context, clientTerminateWorkflowInput *internal.ClientTerminateWorkflowInput) error) *ClientOutboundInterceptor_TerminateWorkflow_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateWithStartWorkflow provides a mock function for the type ClientOutboundInterceptor
func (_mock *ClientOutboundInterceptor) UpdateWithStartWorkflow(context1 context.Context, clientUpdateWithStartWorkflowInput *internal.ClientUpdateWithStartWorkflowInput) (internal.WorkflowUpdateHandle, error) {
	ret := _mock.Called(context1, clientUpdateWithStartWorkflowInput)

	if len(ret) == 0 {
		panic("no return value specified for UpdateWithStartWorkflow")
	}

	var r0 internal.WorkflowUpdateHandle
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *internal.ClientUpdateWithStartWorkflowInput) (internal.WorkflowUpdateHandle, error)); ok {
		return returnFunc(context1, clientUpdateWithStartWorkflowInput)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *internal.ClientUpdateWithStartWorkflowInput) internal.WorkflowUpdateHandle); ok {
		r0 = returnFunc(context1, clientUpdateWithStartWorkflowInput)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(internal.WorkflowUpdateHandle)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *internal.ClientUpdateWithStartWorkflowInput) error); ok {
		r1 = returnFunc(context1, clientUpdateWithStartWorkflowInput)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ClientOutboundInterceptor_UpdateWithStartWorkflow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateWithStartWorkflow'
type ClientOutboundInterceptor_UpdateWithStartWorkflow_Call struct {
	*mock.Call
}

// UpdateWithStartWorkflow is a helper method to define mock.On call
//   - context1 context.Context
//   - clientUpdateWithStartWorkflowInput *internal.ClientUpdateWithStartWorkflowInput
func (_e *ClientOutboundInterceptor_Expecter) UpdateWithStartWorkflow(context1 interface{}, clientUpdateWithStartWorkflowInput interface{}) *ClientOutboundInterceptor_UpdateWithStartWorkflow_Call {
	return &ClientOutboundInterceptor_UpdateWithStartWorkflow_Call{Call: _e.mock.On("UpdateWithStartWorkflow", context1, clientUpdateWithStartWorkflowInput)}
}

func (_c *ClientOutboundInterceptor_UpdateWithStartWorkflow_Call) Run(run func(context1 context.Context, clientUpdateWithStartWorkflowInput *internal.ClientUpdateWithStartWorkflowInput)) *ClientOutboundInterceptor_UpdateWithStartWorkflow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *internal.ClientUpdateWithStartWorkflowInput
		if args[1] != nil {
			arg1 = args[1].(*internal.ClientUpdateWithStartWorkflowInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ClientOutboundInterceptor_UpdateWithStartWorkflow_Call) Return(workflowUpdateHandle internal.WorkflowUpdateHandle, err error) *ClientOutboundInterceptor_UpdateWithStartWorkflow_Call {
	_c.Call.Return(workflowUpdateHandle, err)
	return _c
}

func (_c *ClientOutboundInterceptor_UpdateWithStartWorkflow_Call) RunAndReturn(run func(context1 context.Context, clientUpdateWithStartWorkflowInput *internal.ClientUpdateWithStartWorkflowInput) (internal.WorkflowUpdateHandle, error)) *ClientOutboundInterceptor_UpdateWithStartWorkflow_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateWorkflow provides a mock function for the type ClientOutboundInterceptor
func (_mock *ClientOutboundInterceptor) UpdateWorkflow(context1 context.Context, clientUpdateWorkflowInput *internal.ClientUpdateWorkflowInput) (internal.WorkflowUpdateHandle, error) {
	ret := _mock.Called(context1, clientUpdateWorkflowInput)

	if len(ret) == 0 {
		panic("no return value specified for UpdateWorkflow")
	}

	var r0 internal.WorkflowUpdateHandle
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *internal.ClientUpdateWorkflowInput) (internal.WorkflowUpdateHandle, error)); ok {
		return returnFunc(context1, clientUpdateWorkflowInput)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *internal.ClientUpdateWorkflowInput) internal.WorkflowUpdateHandle); ok {
		r0 = returnFunc(context1, clientUpdateWorkflowInput)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(internal.WorkflowUpdateHandle)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *internal.ClientUpdateWorkflowInput) error); ok {
		r1 = returnFunc(context1, clientUpdateWorkflowInput)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ClientOutboundInterceptor_UpdateWorkflow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateWorkflow'
type ClientOutboundInterceptor_UpdateWorkflow_Call struct {
	*mock.Call
}

// UpdateWorkflow is a helper method to define mock.On call
//   - context1 context.Context
//   - clientUpdateWorkflowInput *internal.ClientUpdateWorkflowInput
func (_e *ClientOutboundInterceptor_Expecter) UpdateWorkflow(context1 interface{}, clientUpdateWorkflowInput interface{}) *ClientOutboundInterceptor_UpdateWorkflow_Call {
	return &ClientOutboundInterceptor_UpdateWorkflow_Call{Call: _e.mock.On("UpdateWorkflow", context1, clientUpdateWorkflowInput)}
}

func (_c *ClientOutboundInterceptor_UpdateWorkflow_Call) Run(run func(context1 context.Context, clientUpdateWorkflowInput *internal.ClientUpdateWorkflowInput)) *ClientOutboundInterceptor_UpdateWorkflow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *internal.ClientUpdateWorkflowInput
		if args[1] != nil {
			arg1 = args[1].(*internal.ClientUpdateWorkflowInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ClientOutboundInterceptor_UpdateWorkflow_Call) Return(workflowUpdateHandle internal.WorkflowUpdateHandle, err error) *ClientOutboundInterceptor_UpdateWorkflow_Call {
	_c.Call.Return(workflowUpdateHandle, err)
	return _c
}

func (_c *ClientOutboundInterceptor_UpdateWorkflow_Call) RunAndReturn(run func(context1 context.Context, clientUpdateWorkflowInput *internal.ClientUpdateWorkflowInput) (internal.WorkflowUpdateHandle, error)) *ClientOutboundInterceptor_UpdateWorkflow_Call {
	_c.Call.Return(run)
	return _c
}

// mustEmbedClientOutboundInterceptorBase provides a mock function for the type ClientOutboundInterceptor
func (_mock *ClientOutboundInterceptor) mustEmbedClientOutboundInterceptorBase() {
	_mock.Called()
	return
}

// ClientOutboundInterceptor_mustEmbedClientOutboundInterceptorBase_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'mustEmbedClientOutboundInterceptorBase'
type ClientOutboundInterceptor_mustEmbedClientOutboundInterceptorBase_Call struct {
	*mock.Call
}

// mustEmbedClientOutboundInterceptorBase is a helper method to define mock.On call
func (_e *ClientOutboundInterceptor_Expecter) mustEmbedClientOutboundInterceptorBase() *ClientOutboundInterceptor_mustEmbedClientOutboundInterceptorBase_Call {
	return &ClientOutboundInterceptor_mustEmbedClientOutboundInterceptorBase_Call{Call: _e.mock.On("mustEmbedClientOutboundInterceptorBase")}
}

func (_c *ClientOutboundInterceptor_mustEmbedClientOutboundInterceptorBase_Call) Run(run func()) *ClientOutboundInterceptor_mustEmbedClientOutboundInterceptorBase_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ClientOutboundInterceptor_mustEmbedClientOutboundInterceptorBase_Call) Return() *ClientOutboundInterceptor_mustEmbedClientOutboundInterceptorBase_Call {
	_c.Call.Return()
	return _c
}

func (_c *ClientOutboundInterceptor_mustEmbedClientOutboundInterceptorBase_Call) RunAndReturn(run func()) *ClientOutboundInterceptor_mustEmbedClientOutboundInterceptorBase_Call {
	_c.Run(run)
	return _c
}
