// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	"go.temporal.io/sdk/internal"
	"google.golang.org/grpc"
)

// NewCredentials creates a new instance of Credentials. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCredentials(t interface {
	mock.TestingT
	Cleanup(func())
}) *Credentials {
	mock := &Credentials{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Credentials is an autogenerated mock type for the Credentials type
type Credentials struct {
	mock.Mock
}

type Credentials_Expecter struct {
	mock *mock.Mock
}

func (_m *Credentials) EXPECT() *Credentials_Expecter {
	return &Credentials_Expecter{mock: &_m.Mock}
}

// applyToOptions provides a mock function for the type Credentials
func (_mock *Credentials) applyToOptions(connectionOptions *internal.ConnectionOptions) error {
	ret := _mock.Called(connectionOptions)

	if len(ret) == 0 {
		panic("no return value specified for applyToOptions")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*internal.ConnectionOptions) error); ok {
		r0 = returnFunc(connectionOptions)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Credentials_applyToOptions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'applyToOptions'
type Credentials_applyToOptions_Call struct {
	*mock.Call
}

// applyToOptions is a helper method to define mock.On call
//   - connectionOptions *internal.ConnectionOptions
func (_e *Credentials_Expecter) applyToOptions(connectionOptions interface{}) *Credentials_applyToOptions_Call {
	return &Credentials_applyToOptions_Call{Call: _e.mock.On("applyToOptions", connectionOptions)}
}

func (_c *Credentials_applyToOptions_Call) Run(run func(connectionOptions *internal.ConnectionOptions)) *Credentials_applyToOptions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *internal.ConnectionOptions
		if args[0] != nil {
			arg0 = args[0].(*internal.ConnectionOptions)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Credentials_applyToOptions_Call) Return(err error) *Credentials_applyToOptions_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Credentials_applyToOptions_Call) RunAndReturn(run func(connectionOptions *internal.ConnectionOptions) error) *Credentials_applyToOptions_Call {
	_c.Call.Return(run)
	return _c
}

// gRPCInterceptor provides a mock function for the type Credentials
func (_mock *Credentials) gRPCInterceptor() grpc.UnaryClientInterceptor {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for gRPCInterceptor")
	}

	var r0 grpc.UnaryClientInterceptor
	if returnFunc, ok := ret.Get(0).(func() grpc.UnaryClientInterceptor); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(grpc.UnaryClientInterceptor)
		}
	}
	return r0
}

// Credentials_gRPCInterceptor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'gRPCInterceptor'
type Credentials_gRPCInterceptor_Call struct {
	*mock.Call
}

// gRPCInterceptor is a helper method to define mock.On call
func (_e *Credentials_Expecter) gRPCInterceptor() *Credentials_gRPCInterceptor_Call {
	return &Credentials_gRPCInterceptor_Call{Call: _e.mock.On("gRPCInterceptor")}
}

func (_c *Credentials_gRPCInterceptor_Call) Run(run func()) *Credentials_gRPCInterceptor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Credentials_gRPCInterceptor_Call) Return(unaryClientInterceptor grpc.UnaryClientInterceptor) *Credentials_gRPCInterceptor_Call {
	_c.Call.Return(unaryClientInterceptor)
	return _c
}

func (_c *Credentials_gRPCInterceptor_Call) RunAndReturn(run func() grpc.UnaryClientInterceptor) *Credentials_gRPCInterceptor_Call {
	_c.Call.Return(run)
	return _c
}
