// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	"go.temporal.io/api/common/v1"
)

// NewDataConverter creates a new instance of DataConverter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDataConverter(t interface {
	mock.TestingT
	Cleanup(func())
}) *DataConverter {
	mock := &DataConverter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// DataConverter is an autogenerated mock type for the DataConverter type
type DataConverter struct {
	mock.Mock
}

type DataConverter_Expecter struct {
	mock *mock.Mock
}

func (_m *DataConverter) EXPECT() *DataConverter_Expecter {
	return &DataConverter_Expecter{mock: &_m.Mock}
}

// FromPayload provides a mock function for the type DataConverter
func (_mock *DataConverter) FromPayload(payload *common.Payload, valuePtr interface{}) error {
	ret := _mock.Called(payload, valuePtr)

	if len(ret) == 0 {
		panic("no return value specified for FromPayload")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*common.Payload, interface{}) error); ok {
		r0 = returnFunc(payload, valuePtr)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// DataConverter_FromPayload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FromPayload'
type DataConverter_FromPayload_Call struct {
	*mock.Call
}

// FromPayload is a helper method to define mock.On call
//   - payload *common.Payload
//   - valuePtr interface{}
func (_e *DataConverter_Expecter) FromPayload(payload interface{}, valuePtr interface{}) *DataConverter_FromPayload_Call {
	return &DataConverter_FromPayload_Call{Call: _e.mock.On("FromPayload", payload, valuePtr)}
}

func (_c *DataConverter_FromPayload_Call) Run(run func(payload *common.Payload, valuePtr interface{})) *DataConverter_FromPayload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *common.Payload
		if args[0] != nil {
			arg0 = args[0].(*common.Payload)
		}
		var arg1 interface{}
		if args[1] != nil {
			arg1 = args[1].(interface{})
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *DataConverter_FromPayload_Call) Return(err error) *DataConverter_FromPayload_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *DataConverter_FromPayload_Call) RunAndReturn(run func(payload *common.Payload, valuePtr interface{}) error) *DataConverter_FromPayload_Call {
	_c.Call.Return(run)
	return _c
}

// FromPayloads provides a mock function for the type DataConverter
func (_mock *DataConverter) FromPayloads(payloads *common.Payloads, valuePtrs ...interface{}) error {
	var tmpRet mock.Arguments
	if len(valuePtrs) > 0 {
		tmpRet = _mock.Called(payloads, valuePtrs)
	} else {
		tmpRet = _mock.Called(payloads)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for FromPayloads")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*common.Payloads, ...interface{}) error); ok {
		r0 = returnFunc(payloads, valuePtrs...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// DataConverter_FromPayloads_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FromPayloads'
type DataConverter_FromPayloads_Call struct {
	*mock.Call
}

// FromPayloads is a helper method to define mock.On call
//   - payloads *common.Payloads
//   - valuePtrs ...interface{}
func (_e *DataConverter_Expecter) FromPayloads(payloads interface{}, valuePtrs ...interface{}) *DataConverter_FromPayloads_Call {
	return &DataConverter_FromPayloads_Call{Call: _e.mock.On("FromPayloads",
		append([]interface{}{payloads}, valuePtrs...)...)}
}

func (_c *DataConverter_FromPayloads_Call) Run(run func(payloads *common.Payloads, valuePtrs ...interface{})) *DataConverter_FromPayloads_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *common.Payloads
		if args[0] != nil {
			arg0 = args[0].(*common.Payloads)
		}
		var arg1 []interface{}
		var variadicArgs []interface{}
		if len(args) > 1 {
			variadicArgs = args[1].([]interface{})
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *DataConverter_FromPayloads_Call) Return(err error) *DataConverter_FromPayloads_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *DataConverter_FromPayloads_Call) RunAndReturn(run func(payloads *common.Payloads, valuePtrs ...interface{}) error) *DataConverter_FromPayloads_Call {
	_c.Call.Return(run)
	return _c
}

// ToPayload provides a mock function for the type DataConverter
func (_mock *DataConverter) ToPayload(value interface{}) (*common.Payload, error) {
	ret := _mock.Called(value)

	if len(ret) == 0 {
		panic("no return value specified for ToPayload")
	}

	var r0 *common.Payload
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(interface{}) (*common.Payload, error)); ok {
		return returnFunc(value)
	}
	if returnFunc, ok := ret.Get(0).(func(interface{}) *common.Payload); ok {
		r0 = returnFunc(value)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*common.Payload)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(interface{}) error); ok {
		r1 = returnFunc(value)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DataConverter_ToPayload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ToPayload'
type DataConverter_ToPayload_Call struct {
	*mock.Call
}

// ToPayload is a helper method to define mock.On call
//   - value interface{}
func (_e *DataConverter_Expecter) ToPayload(value interface{}) *DataConverter_ToPayload_Call {
	return &DataConverter_ToPayload_Call{Call: _e.mock.On("ToPayload", value)}
}

func (_c *DataConverter_ToPayload_Call) Run(run func(value interface{})) *DataConverter_ToPayload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 interface{}
		if args[0] != nil {
			arg0 = args[0].(interface{})
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *DataConverter_ToPayload_Call) Return(payload *common.Payload, err error) *DataConverter_ToPayload_Call {
	_c.Call.Return(payload, err)
	return _c
}

func (_c *DataConverter_ToPayload_Call) RunAndReturn(run func(value interface{}) (*common.Payload, error)) *DataConverter_ToPayload_Call {
	_c.Call.Return(run)
	return _c
}

// ToPayloads provides a mock function for the type DataConverter
func (_mock *DataConverter) ToPayloads(value ...interface{}) (*common.Payloads, error) {
	var tmpRet mock.Arguments
	if len(value) > 0 {
		tmpRet = _mock.Called(value)
	} else {
		tmpRet = _mock.Called()
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for ToPayloads")
	}

	var r0 *common.Payloads
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(...interface{}) (*common.Payloads, error)); ok {
		return returnFunc(value...)
	}
	if returnFunc, ok := ret.Get(0).(func(...interface{}) *common.Payloads); ok {
		r0 = returnFunc(value...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*common.Payloads)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(...interface{}) error); ok {
		r1 = returnFunc(value...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DataConverter_ToPayloads_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ToPayloads'
type DataConverter_ToPayloads_Call struct {
	*mock.Call
}

// ToPayloads is a helper method to define mock.On call
//   - value ...interface{}
func (_e *DataConverter_Expecter) ToPayloads(value ...interface{}) *DataConverter_ToPayloads_Call {
	return &DataConverter_ToPayloads_Call{Call: _e.mock.On("ToPayloads",
		append([]interface{}{}, value...)...)}
}

func (_c *DataConverter_ToPayloads_Call) Run(run func(value ...interface{})) *DataConverter_ToPayloads_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []interface{}
		var variadicArgs []interface{}
		if len(args) > 0 {
			variadicArgs = args[0].([]interface{})
		}
		arg0 = variadicArgs
		run(
			arg0...,
		)
	})
	return _c
}

func (_c *DataConverter_ToPayloads_Call) Return(payloads *common.Payloads, err error) *DataConverter_ToPayloads_Call {
	_c.Call.Return(payloads, err)
	return _c
}

func (_c *DataConverter_ToPayloads_Call) RunAndReturn(run func(value ...interface{}) (*common.Payloads, error)) *DataConverter_ToPayloads_Call {
	_c.Call.Return(run)
	return _c
}

// ToString provides a mock function for the type DataConverter
func (_mock *DataConverter) ToString(input *common.Payload) string {
	ret := _mock.Called(input)

	if len(ret) == 0 {
		panic("no return value specified for ToString")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(*common.Payload) string); ok {
		r0 = returnFunc(input)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// DataConverter_ToString_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ToString'
type DataConverter_ToString_Call struct {
	*mock.Call
}

// ToString is a helper method to define mock.On call
//   - input *common.Payload
func (_e *DataConverter_Expecter) ToString(input interface{}) *DataConverter_ToString_Call {
	return &DataConverter_ToString_Call{Call: _e.mock.On("ToString", input)}
}

func (_c *DataConverter_ToString_Call) Run(run func(input *common.Payload)) *DataConverter_ToString_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *common.Payload
		if args[0] != nil {
			arg0 = args[0].(*common.Payload)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *DataConverter_ToString_Call) Return(s string) *DataConverter_ToString_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *DataConverter_ToString_Call) RunAndReturn(run func(input *common.Payload) string) *DataConverter_ToString_Call {
	_c.Call.Return(run)
	return _c
}

// ToStrings provides a mock function for the type DataConverter
func (_mock *DataConverter) ToStrings(input *common.Payloads) []string {
	ret := _mock.Called(input)

	if len(ret) == 0 {
		panic("no return value specified for ToStrings")
	}

	var r0 []string
	if returnFunc, ok := ret.Get(0).(func(*common.Payloads) []string); ok {
		r0 = returnFunc(input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	return r0
}

// DataConverter_ToStrings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ToStrings'
type DataConverter_ToStrings_Call struct {
	*mock.Call
}

// ToStrings is a helper method to define mock.On call
//   - input *common.Payloads
func (_e *DataConverter_Expecter) ToStrings(input interface{}) *DataConverter_ToStrings_Call {
	return &DataConverter_ToStrings_Call{Call: _e.mock.On("ToStrings", input)}
}

func (_c *DataConverter_ToStrings_Call) Run(run func(input *common.Payloads)) *DataConverter_ToStrings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *common.Payloads
		if args[0] != nil {
			arg0 = args[0].(*common.Payloads)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *DataConverter_ToStrings_Call) Return(strings []string) *DataConverter_ToStrings_Call {
	_c.Call.Return(strings)
	return _c
}

func (_c *DataConverter_ToStrings_Call) RunAndReturn(run func(input *common.Payloads) []string) *DataConverter_ToStrings_Call {
	_c.Call.Return(run)
	return _c
}
