// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	"go.temporal.io/api/common/v1"
)

// NewHeaderReader creates a new instance of HeaderReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHeaderReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *HeaderReader {
	mock := &HeaderReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// HeaderReader is an autogenerated mock type for the HeaderReader type
type HeaderReader struct {
	mock.Mock
}

type HeaderReader_Expecter struct {
	mock *mock.Mock
}

func (_m *HeaderReader) EXPECT() *HeaderReader_Expecter {
	return &HeaderReader_Expecter{mock: &_m.Mock}
}

// ForEachKey provides a mock function for the type HeaderReader
func (_mock *HeaderReader) ForEachKey(handler func(string, *common.Payload) error) error {
	ret := _mock.Called(handler)

	if len(ret) == 0 {
		panic("no return value specified for ForEachKey")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(func(string, *common.Payload) error) error); ok {
		r0 = returnFunc(handler)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// HeaderReader_ForEachKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ForEachKey'
type HeaderReader_ForEachKey_Call struct {
	*mock.Call
}

// ForEachKey is a helper method to define mock.On call
//   - handler func(string, *common.Payload) error
func (_e *HeaderReader_Expecter) ForEachKey(handler interface{}) *HeaderReader_ForEachKey_Call {
	return &HeaderReader_ForEachKey_Call{Call: _e.mock.On("ForEachKey", handler)}
}

func (_c *HeaderReader_ForEachKey_Call) Run(run func(handler func(string, *common.Payload) error)) *HeaderReader_ForEachKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 func(string, *common.Payload) error
		if args[0] != nil {
			arg0 = args[0].(func(string, *common.Payload) error)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *HeaderReader_ForEachKey_Call) Return(err error) *HeaderReader_ForEachKey_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *HeaderReader_ForEachKey_Call) RunAndReturn(run func(handler func(string, *common.Payload) error) error) *HeaderReader_ForEachKey_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type HeaderReader
func (_mock *HeaderReader) Get(s string) (*common.Payload, bool) {
	ret := _mock.Called(s)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *common.Payload
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(string) (*common.Payload, bool)); ok {
		return returnFunc(s)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *common.Payload); ok {
		r0 = returnFunc(s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*common.Payload)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) bool); ok {
		r1 = returnFunc(s)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// HeaderReader_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type HeaderReader_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - s string
func (_e *HeaderReader_Expecter) Get(s interface{}) *HeaderReader_Get_Call {
	return &HeaderReader_Get_Call{Call: _e.mock.On("Get", s)}
}

func (_c *HeaderReader_Get_Call) Run(run func(s string)) *HeaderReader_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *HeaderReader_Get_Call) Return(payload *common.Payload, b bool) *HeaderReader_Get_Call {
	_c.Call.Return(payload, b)
	return _c
}

func (_c *HeaderReader_Get_Call) RunAndReturn(run func(s string) (*common.Payload, bool)) *HeaderReader_Get_Call {
	_c.Call.Return(run)
	return _c
}
