// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	"go.temporal.io/api/history/v1"
)

// NewHistoryEventIterator creates a new instance of HistoryEventIterator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHistoryEventIterator(t interface {
	mock.TestingT
	Cleanup(func())
}) *HistoryEventIterator {
	mock := &HistoryEventIterator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// HistoryEventIterator is an autogenerated mock type for the HistoryEventIterator type
type HistoryEventIterator struct {
	mock.Mock
}

type HistoryEventIterator_Expecter struct {
	mock *mock.Mock
}

func (_m *HistoryEventIterator) EXPECT() *HistoryEventIterator_Expecter {
	return &HistoryEventIterator_Expecter{mock: &_m.Mock}
}

// HasNext provides a mock function for the type HistoryEventIterator
func (_mock *HistoryEventIterator) HasNext() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for HasNext")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// HistoryEventIterator_HasNext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasNext'
type HistoryEventIterator_HasNext_Call struct {
	*mock.Call
}

// HasNext is a helper method to define mock.On call
func (_e *HistoryEventIterator_Expecter) HasNext() *HistoryEventIterator_HasNext_Call {
	return &HistoryEventIterator_HasNext_Call{Call: _e.mock.On("HasNext")}
}

func (_c *HistoryEventIterator_HasNext_Call) Run(run func()) *HistoryEventIterator_HasNext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *HistoryEventIterator_HasNext_Call) Return(b bool) *HistoryEventIterator_HasNext_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *HistoryEventIterator_HasNext_Call) RunAndReturn(run func() bool) *HistoryEventIterator_HasNext_Call {
	_c.Call.Return(run)
	return _c
}

// Next provides a mock function for the type HistoryEventIterator
func (_mock *HistoryEventIterator) Next() (*history.HistoryEvent, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Next")
	}

	var r0 *history.HistoryEvent
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (*history.HistoryEvent, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() *history.HistoryEvent); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*history.HistoryEvent)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// HistoryEventIterator_Next_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Next'
type HistoryEventIterator_Next_Call struct {
	*mock.Call
}

// Next is a helper method to define mock.On call
func (_e *HistoryEventIterator_Expecter) Next() *HistoryEventIterator_Next_Call {
	return &HistoryEventIterator_Next_Call{Call: _e.mock.On("Next")}
}

func (_c *HistoryEventIterator_Next_Call) Run(run func()) *HistoryEventIterator_Next_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *HistoryEventIterator_Next_Call) Return(historyEvent *history.HistoryEvent, err error) *HistoryEventIterator_Next_Call {
	_c.Call.Return(historyEvent, err)
	return _c
}

func (_c *HistoryEventIterator_Next_Call) RunAndReturn(run func() (*history.HistoryEvent, error)) *HistoryEventIterator_Next_Call {
	_c.Call.Return(run)
	return _c
}
