// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"go.temporal.io/api/workflowservice/v1"
)

// NewNamespaceClient creates a new instance of NamespaceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNamespaceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *NamespaceClient {
	mock := &NamespaceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// NamespaceClient is an autogenerated mock type for the NamespaceClient type
type NamespaceClient struct {
	mock.Mock
}

type NamespaceClient_Expecter struct {
	mock *mock.Mock
}

func (_m *NamespaceClient) EXPECT() *NamespaceClient_Expecter {
	return &NamespaceClient_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type NamespaceClient
func (_mock *NamespaceClient) Close() {
	_mock.Called()
	return
}

// NamespaceClient_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type NamespaceClient_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *NamespaceClient_Expecter) Close() *NamespaceClient_Close_Call {
	return &NamespaceClient_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *NamespaceClient_Close_Call) Run(run func()) *NamespaceClient_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *NamespaceClient_Close_Call) Return() *NamespaceClient_Close_Call {
	_c.Call.Return()
	return _c
}

func (_c *NamespaceClient_Close_Call) RunAndReturn(run func()) *NamespaceClient_Close_Call {
	_c.Run(run)
	return _c
}

// Describe provides a mock function for the type NamespaceClient
func (_mock *NamespaceClient) Describe(ctx context.Context, name string) (*workflowservice.DescribeNamespaceResponse, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for Describe")
	}

	var r0 *workflowservice.DescribeNamespaceResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*workflowservice.DescribeNamespaceResponse, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *workflowservice.DescribeNamespaceResponse); ok {
		r0 = returnFunc(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*workflowservice.DescribeNamespaceResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// NamespaceClient_Describe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Describe'
type NamespaceClient_Describe_Call struct {
	*mock.Call
}

// Describe is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *NamespaceClient_Expecter) Describe(ctx interface{}, name interface{}) *NamespaceClient_Describe_Call {
	return &NamespaceClient_Describe_Call{Call: _e.mock.On("Describe", ctx, name)}
}

func (_c *NamespaceClient_Describe_Call) Run(run func(ctx context.Context, name string)) *NamespaceClient_Describe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *NamespaceClient_Describe_Call) Return(describeNamespaceResponse *workflowservice.DescribeNamespaceResponse, err error) *NamespaceClient_Describe_Call {
	_c.Call.Return(describeNamespaceResponse, err)
	return _c
}

func (_c *NamespaceClient_Describe_Call) RunAndReturn(run func(ctx context.Context, name string) (*workflowservice.DescribeNamespaceResponse, error)) *NamespaceClient_Describe_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function for the type NamespaceClient
func (_mock *NamespaceClient) Register(ctx context.Context, request *workflowservice.RegisterNamespaceRequest) error {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *workflowservice.RegisterNamespaceRequest) error); ok {
		r0 = returnFunc(ctx, request)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// NamespaceClient_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type NamespaceClient_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - request *workflowservice.RegisterNamespaceRequest
func (_e *NamespaceClient_Expecter) Register(ctx interface{}, request interface{}) *NamespaceClient_Register_Call {
	return &NamespaceClient_Register_Call{Call: _e.mock.On("Register", ctx, request)}
}

func (_c *NamespaceClient_Register_Call) Run(run func(ctx context.Context, request *workflowservice.RegisterNamespaceRequest)) *NamespaceClient_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *workflowservice.RegisterNamespaceRequest
		if args[1] != nil {
			arg1 = args[1].(*workflowservice.RegisterNamespaceRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *NamespaceClient_Register_Call) Return(err error) *NamespaceClient_Register_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *NamespaceClient_Register_Call) RunAndReturn(run func(ctx context.Context, request *workflowservice.RegisterNamespaceRequest) error) *NamespaceClient_Register_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type NamespaceClient
func (_mock *NamespaceClient) Update(ctx context.Context, request *workflowservice.UpdateNamespaceRequest) error {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *workflowservice.UpdateNamespaceRequest) error); ok {
		r0 = returnFunc(ctx, request)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// NamespaceClient_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type NamespaceClient_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - request *workflowservice.UpdateNamespaceRequest
func (_e *NamespaceClient_Expecter) Update(ctx interface{}, request interface{}) *NamespaceClient_Update_Call {
	return &NamespaceClient_Update_Call{Call: _e.mock.On("Update", ctx, request)}
}

func (_c *NamespaceClient_Update_Call) Run(run func(ctx context.Context, request *workflowservice.UpdateNamespaceRequest)) *NamespaceClient_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *workflowservice.UpdateNamespaceRequest
		if args[1] != nil {
			arg1 = args[1].(*workflowservice.UpdateNamespaceRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *NamespaceClient_Update_Call) Return(err error) *NamespaceClient_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *NamespaceClient_Update_Call) RunAndReturn(run func(ctx context.Context, request *workflowservice.UpdateNamespaceRequest) error) *NamespaceClient_Update_Call {
	_c.Call.Return(run)
	return _c
}
