// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/nexus-rpc/sdk-go/nexus"
	mock "github.com/stretchr/testify/mock"
)

// NewNexusServiceRegistry creates a new instance of NexusServiceRegistry. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNexusServiceRegistry(t interface {
	mock.TestingT
	Cleanup(func())
}) *NexusServiceRegistry {
	mock := &NexusServiceRegistry{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// NexusServiceRegistry is an autogenerated mock type for the NexusServiceRegistry type
type NexusServiceRegistry struct {
	mock.Mock
}

type NexusServiceRegistry_Expecter struct {
	mock *mock.Mock
}

func (_m *NexusServiceRegistry) EXPECT() *NexusServiceRegistry_Expecter {
	return &NexusServiceRegistry_Expecter{mock: &_m.Mock}
}

// RegisterNexusService provides a mock function for the type NexusServiceRegistry
func (_mock *NexusServiceRegistry) RegisterNexusService(service *nexus.Service) {
	_mock.Called(service)
	return
}

// NexusServiceRegistry_RegisterNexusService_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterNexusService'
type NexusServiceRegistry_RegisterNexusService_Call struct {
	*mock.Call
}

// RegisterNexusService is a helper method to define mock.On call
//   - service *nexus.Service
func (_e *NexusServiceRegistry_Expecter) RegisterNexusService(service interface{}) *NexusServiceRegistry_RegisterNexusService_Call {
	return &NexusServiceRegistry_RegisterNexusService_Call{Call: _e.mock.On("RegisterNexusService", service)}
}

func (_c *NexusServiceRegistry_RegisterNexusService_Call) Run(run func(service *nexus.Service)) *NexusServiceRegistry_RegisterNexusService_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *nexus.Service
		if args[0] != nil {
			arg0 = args[0].(*nexus.Service)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *NexusServiceRegistry_RegisterNexusService_Call) Return() *NexusServiceRegistry_RegisterNexusService_Call {
	_c.Call.Return()
	return _c
}

func (_c *NexusServiceRegistry_RegisterNexusService_Call) RunAndReturn(run func(service *nexus.Service)) *NexusServiceRegistry_RegisterNexusService_Call {
	_c.Run(run)
	return _c
}
