// The MIT License
//
// Copyright (c) 2020 Temporal Technologies Inc.  All rights reserved.
//
// Copyright (c) 2020 Uber Technologies, Inc.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

// Code generated by mockery v1.0.0.
// Modified manually for type alias to work correctly.
// https://github.com/vektra/mockery/issues/236

package mocks

import (
	"context"
	"go.temporal.io/sdk/client"

	"github.com/stretchr/testify/mock"
)

// ScheduleClient is an autogenerated mock type for the ScheduleClient type
type ScheduleClient struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, options
func (_m *ScheduleClient) Create(ctx context.Context, options client.ScheduleOptions) (client.ScheduleHandle, error) {
	ret := _m.Called(ctx, options)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 client.ScheduleHandle
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, client.ScheduleOptions) (client.ScheduleHandle, error)); ok {
		return rf(ctx, options)
	}
	if rf, ok := ret.Get(0).(func(context.Context, client.ScheduleOptions) client.ScheduleHandle); ok {
		r0 = rf(ctx, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(client.ScheduleHandle)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, client.ScheduleOptions) error); ok {
		r1 = rf(ctx, options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetHandle provides a mock function with given fields: ctx, scheduleID
func (_m *ScheduleClient) GetHandle(ctx context.Context, scheduleID string) client.ScheduleHandle {
	ret := _m.Called(ctx, scheduleID)

	if len(ret) == 0 {
		panic("no return value specified for GetHandle")
	}

	var r0 client.ScheduleHandle
	if rf, ok := ret.Get(0).(func(context.Context, string) client.ScheduleHandle); ok {
		r0 = rf(ctx, scheduleID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(client.ScheduleHandle)
		}
	}

	return r0
}

// List provides a mock function with given fields: ctx, options
func (_m *ScheduleClient) List(ctx context.Context, options client.ScheduleListOptions) (client.ScheduleListIterator, error) {
	ret := _m.Called(ctx, options)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 client.ScheduleListIterator
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, client.ScheduleListOptions) (client.ScheduleListIterator, error)); ok {
		return rf(ctx, options)
	}
	if rf, ok := ret.Get(0).(func(context.Context, client.ScheduleListOptions) client.ScheduleListIterator); ok {
		r0 = rf(ctx, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(client.ScheduleListIterator)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, client.ScheduleListOptions) error); ok {
		r1 = rf(ctx, options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewScheduleClient creates a new instance of ScheduleClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewScheduleClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *ScheduleClient {
	mock := &ScheduleClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
