// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewScheduleAction creates a new instance of ScheduleAction. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewScheduleAction(t interface {
	mock.TestingT
	Cleanup(func())
}) *ScheduleAction {
	mock := &ScheduleAction{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ScheduleAction is an autogenerated mock type for the ScheduleAction type
type ScheduleAction struct {
	mock.Mock
}

type ScheduleAction_Expecter struct {
	mock *mock.Mock
}

func (_m *ScheduleAction) EXPECT() *ScheduleAction_Expecter {
	return &ScheduleAction_Expecter{mock: &_m.Mock}
}

// isScheduleAction provides a mock function for the type ScheduleAction
func (_mock *ScheduleAction) isScheduleAction() {
	_mock.Called()
	return
}

// ScheduleAction_isScheduleAction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'isScheduleAction'
type ScheduleAction_isScheduleAction_Call struct {
	*mock.Call
}

// isScheduleAction is a helper method to define mock.On call
func (_e *ScheduleAction_Expecter) isScheduleAction() *ScheduleAction_isScheduleAction_Call {
	return &ScheduleAction_isScheduleAction_Call{Call: _e.mock.On("isScheduleAction")}
}

func (_c *ScheduleAction_isScheduleAction_Call) Run(run func()) *ScheduleAction_isScheduleAction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ScheduleAction_isScheduleAction_Call) Return() *ScheduleAction_isScheduleAction_Call {
	_c.Call.Return()
	return _c
}

func (_c *ScheduleAction_isScheduleAction_Call) RunAndReturn(run func()) *ScheduleAction_isScheduleAction_Call {
	_c.Run(run)
	return _c
}
