// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	"go.temporal.io/sdk/internal"
)

// NewScheduleListIterator creates a new instance of ScheduleListIterator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewScheduleListIterator(t interface {
	mock.TestingT
	Cleanup(func())
}) *ScheduleListIterator {
	mock := &ScheduleListIterator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ScheduleListIterator is an autogenerated mock type for the ScheduleListIterator type
type ScheduleListIterator struct {
	mock.Mock
}

type ScheduleListIterator_Expecter struct {
	mock *mock.Mock
}

func (_m *ScheduleListIterator) EXPECT() *ScheduleListIterator_Expecter {
	return &ScheduleListIterator_Expecter{mock: &_m.Mock}
}

// HasNext provides a mock function for the type ScheduleListIterator
func (_mock *ScheduleListIterator) HasNext() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for HasNext")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// ScheduleListIterator_HasNext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasNext'
type ScheduleListIterator_HasNext_Call struct {
	*mock.Call
}

// HasNext is a helper method to define mock.On call
func (_e *ScheduleListIterator_Expecter) HasNext() *ScheduleListIterator_HasNext_Call {
	return &ScheduleListIterator_HasNext_Call{Call: _e.mock.On("HasNext")}
}

func (_c *ScheduleListIterator_HasNext_Call) Run(run func()) *ScheduleListIterator_HasNext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ScheduleListIterator_HasNext_Call) Return(b bool) *ScheduleListIterator_HasNext_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *ScheduleListIterator_HasNext_Call) RunAndReturn(run func() bool) *ScheduleListIterator_HasNext_Call {
	_c.Call.Return(run)
	return _c
}

// Next provides a mock function for the type ScheduleListIterator
func (_mock *ScheduleListIterator) Next() (*internal.ScheduleListEntry, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Next")
	}

	var r0 *internal.ScheduleListEntry
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (*internal.ScheduleListEntry, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() *internal.ScheduleListEntry); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*internal.ScheduleListEntry)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ScheduleListIterator_Next_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Next'
type ScheduleListIterator_Next_Call struct {
	*mock.Call
}

// Next is a helper method to define mock.On call
func (_e *ScheduleListIterator_Expecter) Next() *ScheduleListIterator_Next_Call {
	return &ScheduleListIterator_Next_Call{Call: _e.mock.On("Next")}
}

func (_c *ScheduleListIterator_Next_Call) Run(run func()) *ScheduleListIterator_Next_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ScheduleListIterator_Next_Call) Return(scheduleListEntry *internal.ScheduleListEntry, err error) *ScheduleListIterator_Next_Call {
	_c.Call.Return(scheduleListEntry, err)
	return _c
}

func (_c *ScheduleListIterator_Next_Call) RunAndReturn(run func() (*internal.ScheduleListEntry, error)) *ScheduleListIterator_Next_Call {
	_c.Call.Return(run)
	return _c
}
