// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"reflect"

	mock "github.com/stretchr/testify/mock"
	"go.temporal.io/api/enums/v1"
)

// NewSearchAttributeKey creates a new instance of SearchAttributeKey. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSearchAttributeKey(t interface {
	mock.TestingT
	Cleanup(func())
}) *SearchAttributeKey {
	mock := &SearchAttributeKey{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// SearchAttributeKey is an autogenerated mock type for the SearchAttributeKey type
type SearchAttributeKey struct {
	mock.Mock
}

type SearchAttributeKey_Expecter struct {
	mock *mock.Mock
}

func (_m *SearchAttributeKey) EXPECT() *SearchAttributeKey_Expecter {
	return &SearchAttributeKey_Expecter{mock: &_m.Mock}
}

// GetName provides a mock function for the type SearchAttributeKey
func (_mock *SearchAttributeKey) GetName() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetName")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// SearchAttributeKey_GetName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetName'
type SearchAttributeKey_GetName_Call struct {
	*mock.Call
}

// GetName is a helper method to define mock.On call
func (_e *SearchAttributeKey_Expecter) GetName() *SearchAttributeKey_GetName_Call {
	return &SearchAttributeKey_GetName_Call{Call: _e.mock.On("GetName")}
}

func (_c *SearchAttributeKey_GetName_Call) Run(run func()) *SearchAttributeKey_GetName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *SearchAttributeKey_GetName_Call) Return(s string) *SearchAttributeKey_GetName_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *SearchAttributeKey_GetName_Call) RunAndReturn(run func() string) *SearchAttributeKey_GetName_Call {
	_c.Call.Return(run)
	return _c
}

// GetReflectType provides a mock function for the type SearchAttributeKey
func (_mock *SearchAttributeKey) GetReflectType() reflect.Type {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetReflectType")
	}

	var r0 reflect.Type
	if returnFunc, ok := ret.Get(0).(func() reflect.Type); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(reflect.Type)
		}
	}
	return r0
}

// SearchAttributeKey_GetReflectType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetReflectType'
type SearchAttributeKey_GetReflectType_Call struct {
	*mock.Call
}

// GetReflectType is a helper method to define mock.On call
func (_e *SearchAttributeKey_Expecter) GetReflectType() *SearchAttributeKey_GetReflectType_Call {
	return &SearchAttributeKey_GetReflectType_Call{Call: _e.mock.On("GetReflectType")}
}

func (_c *SearchAttributeKey_GetReflectType_Call) Run(run func()) *SearchAttributeKey_GetReflectType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *SearchAttributeKey_GetReflectType_Call) Return(typeParam reflect.Type) *SearchAttributeKey_GetReflectType_Call {
	_c.Call.Return(typeParam)
	return _c
}

func (_c *SearchAttributeKey_GetReflectType_Call) RunAndReturn(run func() reflect.Type) *SearchAttributeKey_GetReflectType_Call {
	_c.Call.Return(run)
	return _c
}

// GetValueType provides a mock function for the type SearchAttributeKey
func (_mock *SearchAttributeKey) GetValueType() enums.IndexedValueType {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetValueType")
	}

	var r0 enums.IndexedValueType
	if returnFunc, ok := ret.Get(0).(func() enums.IndexedValueType); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(enums.IndexedValueType)
	}
	return r0
}

// SearchAttributeKey_GetValueType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetValueType'
type SearchAttributeKey_GetValueType_Call struct {
	*mock.Call
}

// GetValueType is a helper method to define mock.On call
func (_e *SearchAttributeKey_Expecter) GetValueType() *SearchAttributeKey_GetValueType_Call {
	return &SearchAttributeKey_GetValueType_Call{Call: _e.mock.On("GetValueType")}
}

func (_c *SearchAttributeKey_GetValueType_Call) Run(run func()) *SearchAttributeKey_GetValueType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *SearchAttributeKey_GetValueType_Call) Return(indexedValueType enums.IndexedValueType) *SearchAttributeKey_GetValueType_Call {
	_c.Call.Return(indexedValueType)
	return _c
}

func (_c *SearchAttributeKey_GetValueType_Call) RunAndReturn(run func() enums.IndexedValueType) *SearchAttributeKey_GetValueType_Call {
	_c.Call.Return(run)
	return _c
}
