// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	"go.temporal.io/sdk/internal"
)

// NewSemaphore creates a new instance of Semaphore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSemaphore(t interface {
	mock.TestingT
	Cleanup(func())
}) *Semaphore {
	mock := &Semaphore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Semaphore is an autogenerated mock type for the Semaphore type
type Semaphore struct {
	mock.Mock
}

type Semaphore_Expecter struct {
	mock *mock.Mock
}

func (_m *Semaphore) EXPECT() *Semaphore_Expecter {
	return &Semaphore_Expecter{mock: &_m.Mock}
}

// Acquire provides a mock function for the type Semaphore
func (_mock *Semaphore) Acquire(ctx internal.Context, n int64) error {
	ret := _mock.Called(ctx, n)

	if len(ret) == 0 {
		panic("no return value specified for Acquire")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(internal.Context, int64) error); ok {
		r0 = returnFunc(ctx, n)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Semaphore_Acquire_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Acquire'
type Semaphore_Acquire_Call struct {
	*mock.Call
}

// Acquire is a helper method to define mock.On call
//   - ctx internal.Context
//   - n int64
func (_e *Semaphore_Expecter) Acquire(ctx interface{}, n interface{}) *Semaphore_Acquire_Call {
	return &Semaphore_Acquire_Call{Call: _e.mock.On("Acquire", ctx, n)}
}

func (_c *Semaphore_Acquire_Call) Run(run func(ctx internal.Context, n int64)) *Semaphore_Acquire_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 internal.Context
		if args[0] != nil {
			arg0 = args[0].(internal.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Semaphore_Acquire_Call) Return(err error) *Semaphore_Acquire_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Semaphore_Acquire_Call) RunAndReturn(run func(ctx internal.Context, n int64) error) *Semaphore_Acquire_Call {
	_c.Call.Return(run)
	return _c
}

// Release provides a mock function for the type Semaphore
func (_mock *Semaphore) Release(n int64) {
	_mock.Called(n)
	return
}

// Semaphore_Release_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Release'
type Semaphore_Release_Call struct {
	*mock.Call
}

// Release is a helper method to define mock.On call
//   - n int64
func (_e *Semaphore_Expecter) Release(n interface{}) *Semaphore_Release_Call {
	return &Semaphore_Release_Call{Call: _e.mock.On("Release", n)}
}

func (_c *Semaphore_Release_Call) Run(run func(n int64)) *Semaphore_Release_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Semaphore_Release_Call) Return() *Semaphore_Release_Call {
	_c.Call.Return()
	return _c
}

func (_c *Semaphore_Release_Call) RunAndReturn(run func(n int64)) *Semaphore_Release_Call {
	_c.Run(run)
	return _c
}

// TryAcquire provides a mock function for the type Semaphore
func (_mock *Semaphore) TryAcquire(ctx internal.Context, n int64) bool {
	ret := _mock.Called(ctx, n)

	if len(ret) == 0 {
		panic("no return value specified for TryAcquire")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(internal.Context, int64) bool); ok {
		r0 = returnFunc(ctx, n)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// Semaphore_TryAcquire_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TryAcquire'
type Semaphore_TryAcquire_Call struct {
	*mock.Call
}

// TryAcquire is a helper method to define mock.On call
//   - ctx internal.Context
//   - n int64
func (_e *Semaphore_Expecter) TryAcquire(ctx interface{}, n interface{}) *Semaphore_TryAcquire_Call {
	return &Semaphore_TryAcquire_Call{Call: _e.mock.On("TryAcquire", ctx, n)}
}

func (_c *Semaphore_TryAcquire_Call) Run(run func(ctx internal.Context, n int64)) *Semaphore_TryAcquire_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 internal.Context
		if args[0] != nil {
			arg0 = args[0].(internal.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Semaphore_TryAcquire_Call) Return(b bool) *Semaphore_TryAcquire_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *Semaphore_TryAcquire_Call) RunAndReturn(run func(ctx internal.Context, n int64) bool) *Semaphore_TryAcquire_Call {
	_c.Call.Return(run)
	return _c
}
