// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	"go.temporal.io/sdk/internal"
)

// NewSettable creates a new instance of Settable. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSettable(t interface {
	mock.TestingT
	Cleanup(func())
}) *Settable {
	mock := &Settable{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Settable is an autogenerated mock type for the Settable type
type Settable struct {
	mock.Mock
}

type Settable_Expecter struct {
	mock *mock.Mock
}

func (_m *Settable) EXPECT() *Settable_Expecter {
	return &Settable_Expecter{mock: &_m.Mock}
}

// Chain provides a mock function for the type Settable
func (_mock *Settable) Chain(future internal.Future) {
	_mock.Called(future)
	return
}

// Settable_Chain_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Chain'
type Settable_Chain_Call struct {
	*mock.Call
}

// Chain is a helper method to define mock.On call
//   - future internal.Future
func (_e *Settable_Expecter) Chain(future interface{}) *Settable_Chain_Call {
	return &Settable_Chain_Call{Call: _e.mock.On("Chain", future)}
}

func (_c *Settable_Chain_Call) Run(run func(future internal.Future)) *Settable_Chain_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 internal.Future
		if args[0] != nil {
			arg0 = args[0].(internal.Future)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Settable_Chain_Call) Return() *Settable_Chain_Call {
	_c.Call.Return()
	return _c
}

func (_c *Settable_Chain_Call) RunAndReturn(run func(future internal.Future)) *Settable_Chain_Call {
	_c.Run(run)
	return _c
}

// Set provides a mock function for the type Settable
func (_mock *Settable) Set(value interface{}, err error) {
	_mock.Called(value, err)
	return
}

// Settable_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type Settable_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - value interface{}
//   - err error
func (_e *Settable_Expecter) Set(value interface{}, err interface{}) *Settable_Set_Call {
	return &Settable_Set_Call{Call: _e.mock.On("Set", value, err)}
}

func (_c *Settable_Set_Call) Run(run func(value interface{}, err error)) *Settable_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 interface{}
		if args[0] != nil {
			arg0 = args[0].(interface{})
		}
		var arg1 error
		if args[1] != nil {
			arg1 = args[1].(error)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Settable_Set_Call) Return() *Settable_Set_Call {
	_c.Call.Return()
	return _c
}

func (_c *Settable_Set_Call) RunAndReturn(run func(value interface{}, err error)) *Settable_Set_Call {
	_c.Run(run)
	return _c
}

// SetError provides a mock function for the type Settable
func (_mock *Settable) SetError(err error) {
	_mock.Called(err)
	return
}

// Settable_SetError_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetError'
type Settable_SetError_Call struct {
	*mock.Call
}

// SetError is a helper method to define mock.On call
//   - err error
func (_e *Settable_Expecter) SetError(err interface{}) *Settable_SetError_Call {
	return &Settable_SetError_Call{Call: _e.mock.On("SetError", err)}
}

func (_c *Settable_SetError_Call) Run(run func(err error)) *Settable_SetError_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 error
		if args[0] != nil {
			arg0 = args[0].(error)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Settable_SetError_Call) Return() *Settable_SetError_Call {
	_c.Call.Return()
	return _c
}

func (_c *Settable_SetError_Call) RunAndReturn(run func(err error)) *Settable_SetError_Call {
	_c.Run(run)
	return _c
}

// SetValue provides a mock function for the type Settable
func (_mock *Settable) SetValue(value interface{}) {
	_mock.Called(value)
	return
}

// Settable_SetValue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetValue'
type Settable_SetValue_Call struct {
	*mock.Call
}

// SetValue is a helper method to define mock.On call
//   - value interface{}
func (_e *Settable_Expecter) SetValue(value interface{}) *Settable_SetValue_Call {
	return &Settable_SetValue_Call{Call: _e.mock.On("SetValue", value)}
}

func (_c *Settable_SetValue_Call) Run(run func(value interface{})) *Settable_SetValue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 interface{}
		if args[0] != nil {
			arg0 = args[0].(interface{})
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Settable_SetValue_Call) Return() *Settable_SetValue_Call {
	_c.Call.Return()
	return _c
}

func (_c *Settable_SetValue_Call) RunAndReturn(run func(value interface{})) *Settable_SetValue_Call {
	_c.Run(run)
	return _c
}
