// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"go.temporal.io/sdk/internal"
)

// NewSlotSupplier creates a new instance of SlotSupplier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSlotSupplier(t interface {
	mock.TestingT
	Cleanup(func())
}) *SlotSupplier {
	mock := &SlotSupplier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// SlotSupplier is an autogenerated mock type for the SlotSupplier type
type SlotSupplier struct {
	mock.Mock
}

type SlotSupplier_Expecter struct {
	mock *mock.Mock
}

func (_m *SlotSupplier) EXPECT() *SlotSupplier_Expecter {
	return &SlotSupplier_Expecter{mock: &_m.Mock}
}

// MarkSlotUsed provides a mock function for the type SlotSupplier
func (_mock *SlotSupplier) MarkSlotUsed(info internal.SlotMarkUsedInfo) {
	_mock.Called(info)
	return
}

// SlotSupplier_MarkSlotUsed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkSlotUsed'
type SlotSupplier_MarkSlotUsed_Call struct {
	*mock.Call
}

// MarkSlotUsed is a helper method to define mock.On call
//   - info internal.SlotMarkUsedInfo
func (_e *SlotSupplier_Expecter) MarkSlotUsed(info interface{}) *SlotSupplier_MarkSlotUsed_Call {
	return &SlotSupplier_MarkSlotUsed_Call{Call: _e.mock.On("MarkSlotUsed", info)}
}

func (_c *SlotSupplier_MarkSlotUsed_Call) Run(run func(info internal.SlotMarkUsedInfo)) *SlotSupplier_MarkSlotUsed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 internal.SlotMarkUsedInfo
		if args[0] != nil {
			arg0 = args[0].(internal.SlotMarkUsedInfo)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *SlotSupplier_MarkSlotUsed_Call) Return() *SlotSupplier_MarkSlotUsed_Call {
	_c.Call.Return()
	return _c
}

func (_c *SlotSupplier_MarkSlotUsed_Call) RunAndReturn(run func(info internal.SlotMarkUsedInfo)) *SlotSupplier_MarkSlotUsed_Call {
	_c.Run(run)
	return _c
}

// MaxSlots provides a mock function for the type SlotSupplier
func (_mock *SlotSupplier) MaxSlots() int {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for MaxSlots")
	}

	var r0 int
	if returnFunc, ok := ret.Get(0).(func() int); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int)
	}
	return r0
}

// SlotSupplier_MaxSlots_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MaxSlots'
type SlotSupplier_MaxSlots_Call struct {
	*mock.Call
}

// MaxSlots is a helper method to define mock.On call
func (_e *SlotSupplier_Expecter) MaxSlots() *SlotSupplier_MaxSlots_Call {
	return &SlotSupplier_MaxSlots_Call{Call: _e.mock.On("MaxSlots")}
}

func (_c *SlotSupplier_MaxSlots_Call) Run(run func()) *SlotSupplier_MaxSlots_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *SlotSupplier_MaxSlots_Call) Return(n int) *SlotSupplier_MaxSlots_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *SlotSupplier_MaxSlots_Call) RunAndReturn(run func() int) *SlotSupplier_MaxSlots_Call {
	_c.Call.Return(run)
	return _c
}

// ReleaseSlot provides a mock function for the type SlotSupplier
func (_mock *SlotSupplier) ReleaseSlot(info internal.SlotReleaseInfo) {
	_mock.Called(info)
	return
}

// SlotSupplier_ReleaseSlot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReleaseSlot'
type SlotSupplier_ReleaseSlot_Call struct {
	*mock.Call
}

// ReleaseSlot is a helper method to define mock.On call
//   - info internal.SlotReleaseInfo
func (_e *SlotSupplier_Expecter) ReleaseSlot(info interface{}) *SlotSupplier_ReleaseSlot_Call {
	return &SlotSupplier_ReleaseSlot_Call{Call: _e.mock.On("ReleaseSlot", info)}
}

func (_c *SlotSupplier_ReleaseSlot_Call) Run(run func(info internal.SlotReleaseInfo)) *SlotSupplier_ReleaseSlot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 internal.SlotReleaseInfo
		if args[0] != nil {
			arg0 = args[0].(internal.SlotReleaseInfo)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *SlotSupplier_ReleaseSlot_Call) Return() *SlotSupplier_ReleaseSlot_Call {
	_c.Call.Return()
	return _c
}

func (_c *SlotSupplier_ReleaseSlot_Call) RunAndReturn(run func(info internal.SlotReleaseInfo)) *SlotSupplier_ReleaseSlot_Call {
	_c.Run(run)
	return _c
}

// ReserveSlot provides a mock function for the type SlotSupplier
func (_mock *SlotSupplier) ReserveSlot(ctx context.Context, info internal.SlotReservationInfo) (*internal.SlotPermit, error) {
	ret := _mock.Called(ctx, info)

	if len(ret) == 0 {
		panic("no return value specified for ReserveSlot")
	}

	var r0 *internal.SlotPermit
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, internal.SlotReservationInfo) (*internal.SlotPermit, error)); ok {
		return returnFunc(ctx, info)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, internal.SlotReservationInfo) *internal.SlotPermit); ok {
		r0 = returnFunc(ctx, info)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*internal.SlotPermit)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, internal.SlotReservationInfo) error); ok {
		r1 = returnFunc(ctx, info)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SlotSupplier_ReserveSlot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReserveSlot'
type SlotSupplier_ReserveSlot_Call struct {
	*mock.Call
}

// ReserveSlot is a helper method to define mock.On call
//   - ctx context.Context
//   - info internal.SlotReservationInfo
func (_e *SlotSupplier_Expecter) ReserveSlot(ctx interface{}, info interface{}) *SlotSupplier_ReserveSlot_Call {
	return &SlotSupplier_ReserveSlot_Call{Call: _e.mock.On("ReserveSlot", ctx, info)}
}

func (_c *SlotSupplier_ReserveSlot_Call) Run(run func(ctx context.Context, info internal.SlotReservationInfo)) *SlotSupplier_ReserveSlot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 internal.SlotReservationInfo
		if args[1] != nil {
			arg1 = args[1].(internal.SlotReservationInfo)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SlotSupplier_ReserveSlot_Call) Return(slotPermit *internal.SlotPermit, err error) *SlotSupplier_ReserveSlot_Call {
	_c.Call.Return(slotPermit, err)
	return _c
}

func (_c *SlotSupplier_ReserveSlot_Call) RunAndReturn(run func(ctx context.Context, info internal.SlotReservationInfo) (*internal.SlotPermit, error)) *SlotSupplier_ReserveSlot_Call {
	_c.Call.Return(run)
	return _c
}

// TryReserveSlot provides a mock function for the type SlotSupplier
func (_mock *SlotSupplier) TryReserveSlot(info internal.SlotReservationInfo) *internal.SlotPermit {
	ret := _mock.Called(info)

	if len(ret) == 0 {
		panic("no return value specified for TryReserveSlot")
	}

	var r0 *internal.SlotPermit
	if returnFunc, ok := ret.Get(0).(func(internal.SlotReservationInfo) *internal.SlotPermit); ok {
		r0 = returnFunc(info)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*internal.SlotPermit)
		}
	}
	return r0
}

// SlotSupplier_TryReserveSlot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TryReserveSlot'
type SlotSupplier_TryReserveSlot_Call struct {
	*mock.Call
}

// TryReserveSlot is a helper method to define mock.On call
//   - info internal.SlotReservationInfo
func (_e *SlotSupplier_Expecter) TryReserveSlot(info interface{}) *SlotSupplier_TryReserveSlot_Call {
	return &SlotSupplier_TryReserveSlot_Call{Call: _e.mock.On("TryReserveSlot", info)}
}

func (_c *SlotSupplier_TryReserveSlot_Call) Run(run func(info internal.SlotReservationInfo)) *SlotSupplier_TryReserveSlot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 internal.SlotReservationInfo
		if args[0] != nil {
			arg0 = args[0].(internal.SlotReservationInfo)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *SlotSupplier_TryReserveSlot_Call) Return(slotPermit *internal.SlotPermit) *SlotSupplier_TryReserveSlot_Call {
	_c.Call.Return(slotPermit)
	return _c
}

func (_c *SlotSupplier_TryReserveSlot_Call) RunAndReturn(run func(info internal.SlotReservationInfo) *internal.SlotPermit) *SlotSupplier_TryReserveSlot_Call {
	_c.Call.Return(run)
	return _c
}
