// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"go.temporal.io/sdk/internal"
)

// NewWithStartWorkflowOperation creates a new instance of WithStartWorkflowOperation. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWithStartWorkflowOperation(t interface {
	mock.TestingT
	Cleanup(func())
}) *WithStartWorkflowOperation {
	mock := &WithStartWorkflowOperation{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// WithStartWorkflowOperation is an autogenerated mock type for the WithStartWorkflowOperation type
type WithStartWorkflowOperation struct {
	mock.Mock
}

type WithStartWorkflowOperation_Expecter struct {
	mock *mock.Mock
}

func (_m *WithStartWorkflowOperation) EXPECT() *WithStartWorkflowOperation_Expecter {
	return &WithStartWorkflowOperation_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type WithStartWorkflowOperation
func (_mock *WithStartWorkflowOperation) Get(ctx context.Context) (internal.WorkflowRun, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 internal.WorkflowRun
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (internal.WorkflowRun, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) internal.WorkflowRun); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(internal.WorkflowRun)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// WithStartWorkflowOperation_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type WithStartWorkflowOperation_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
func (_e *WithStartWorkflowOperation_Expecter) Get(ctx interface{}) *WithStartWorkflowOperation_Get_Call {
	return &WithStartWorkflowOperation_Get_Call{Call: _e.mock.On("Get", ctx)}
}

func (_c *WithStartWorkflowOperation_Get_Call) Run(run func(ctx context.Context)) *WithStartWorkflowOperation_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *WithStartWorkflowOperation_Get_Call) Return(workflowRun internal.WorkflowRun, err error) *WithStartWorkflowOperation_Get_Call {
	_c.Call.Return(workflowRun, err)
	return _c
}

func (_c *WithStartWorkflowOperation_Get_Call) RunAndReturn(run func(ctx context.Context) (internal.WorkflowRun, error)) *WithStartWorkflowOperation_Get_Call {
	_c.Call.Return(run)
	return _c
}
