// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/nexus-rpc/sdk-go/nexus"
	mock "github.com/stretchr/testify/mock"
)

// NewWorkflowHandle creates a new instance of WorkflowHandle. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWorkflowHandle[T any](t interface {
	mock.TestingT
	Cleanup(func())
}) *WorkflowHandle[T] {
	mock := &WorkflowHandle[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// WorkflowHandle is an autogenerated mock type for the WorkflowHandle type
type WorkflowHandle[T any] struct {
	mock.Mock
}

type WorkflowHandle_Expecter[T any] struct {
	mock *mock.Mock
}

func (_m *WorkflowHandle[T]) EXPECT() *WorkflowHandle_Expecter[T] {
	return &WorkflowHandle_Expecter[T]{mock: &_m.Mock}
}

// ID provides a mock function for the type WorkflowHandle
func (_mock *WorkflowHandle[T]) ID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// WorkflowHandle_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type WorkflowHandle_ID_Call[T any] struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
func (_e *WorkflowHandle_Expecter[T]) ID() *WorkflowHandle_ID_Call[T] {
	return &WorkflowHandle_ID_Call[T]{Call: _e.mock.On("ID")}
}

func (_c *WorkflowHandle_ID_Call[T]) Run(run func()) *WorkflowHandle_ID_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *WorkflowHandle_ID_Call[T]) Return(s string) *WorkflowHandle_ID_Call[T] {
	_c.Call.Return(s)
	return _c
}

func (_c *WorkflowHandle_ID_Call[T]) RunAndReturn(run func() string) *WorkflowHandle_ID_Call[T] {
	_c.Call.Return(run)
	return _c
}

// RunID provides a mock function for the type WorkflowHandle
func (_mock *WorkflowHandle[T]) RunID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for RunID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// WorkflowHandle_RunID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RunID'
type WorkflowHandle_RunID_Call[T any] struct {
	*mock.Call
}

// RunID is a helper method to define mock.On call
func (_e *WorkflowHandle_Expecter[T]) RunID() *WorkflowHandle_RunID_Call[T] {
	return &WorkflowHandle_RunID_Call[T]{Call: _e.mock.On("RunID")}
}

func (_c *WorkflowHandle_RunID_Call[T]) Run(run func()) *WorkflowHandle_RunID_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *WorkflowHandle_RunID_Call[T]) Return(s string) *WorkflowHandle_RunID_Call[T] {
	_c.Call.Return(s)
	return _c
}

func (_c *WorkflowHandle_RunID_Call[T]) RunAndReturn(run func() string) *WorkflowHandle_RunID_Call[T] {
	_c.Call.Return(run)
	return _c
}

// link provides a mock function for the type WorkflowHandle
func (_mock *WorkflowHandle[T]) link() nexus.Link {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for link")
	}

	var r0 nexus.Link
	if returnFunc, ok := ret.Get(0).(func() nexus.Link); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(nexus.Link)
	}
	return r0
}

// WorkflowHandle_link_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'link'
type WorkflowHandle_link_Call[T any] struct {
	*mock.Call
}

// link is a helper method to define mock.On call
func (_e *WorkflowHandle_Expecter[T]) link() *WorkflowHandle_link_Call[T] {
	return &WorkflowHandle_link_Call[T]{Call: _e.mock.On("link")}
}

func (_c *WorkflowHandle_link_Call[T]) Run(run func()) *WorkflowHandle_link_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *WorkflowHandle_link_Call[T]) Return(link nexus.Link) *WorkflowHandle_link_Call[T] {
	_c.Call.Return(link)
	return _c
}

func (_c *WorkflowHandle_link_Call[T]) RunAndReturn(run func() nexus.Link) *WorkflowHandle_link_Call[T] {
	_c.Call.Return(run)
	return _c
}

// token provides a mock function for the type WorkflowHandle
func (_mock *WorkflowHandle[T]) token() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for token")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// WorkflowHandle_token_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'token'
type WorkflowHandle_token_Call[T any] struct {
	*mock.Call
}

// token is a helper method to define mock.On call
func (_e *WorkflowHandle_Expecter[T]) token() *WorkflowHandle_token_Call[T] {
	return &WorkflowHandle_token_Call[T]{Call: _e.mock.On("token")}
}

func (_c *WorkflowHandle_token_Call[T]) Run(run func()) *WorkflowHandle_token_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *WorkflowHandle_token_Call[T]) Return(s string) *WorkflowHandle_token_Call[T] {
	_c.Call.Return(s)
	return _c
}

func (_c *WorkflowHandle_token_Call[T]) RunAndReturn(run func() string) *WorkflowHandle_token_Call[T] {
	_c.Call.Return(run)
	return _c
}

// typeMarker provides a mock function for the type WorkflowHandle
func (_mock *WorkflowHandle[T]) typeMarker(v T) {
	_mock.Called(v)
	return
}

// WorkflowHandle_typeMarker_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'typeMarker'
type WorkflowHandle_typeMarker_Call[T any] struct {
	*mock.Call
}

// typeMarker is a helper method to define mock.On call
//   - v T
func (_e *WorkflowHandle_Expecter[T]) typeMarker(v interface{}) *WorkflowHandle_typeMarker_Call[T] {
	return &WorkflowHandle_typeMarker_Call[T]{Call: _e.mock.On("typeMarker", v)}
}

func (_c *WorkflowHandle_typeMarker_Call[T]) Run(run func(v T)) *WorkflowHandle_typeMarker_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 T
		if args[0] != nil {
			arg0 = args[0].(T)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *WorkflowHandle_typeMarker_Call[T]) Return() *WorkflowHandle_typeMarker_Call[T] {
	_c.Call.Return()
	return _c
}

func (_c *WorkflowHandle_typeMarker_Call[T]) RunAndReturn(run func(v T)) *WorkflowHandle_typeMarker_Call[T] {
	_c.Run(run)
	return _c
}
