// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"go.temporal.io/api/history/v1"
	"go.temporal.io/api/workflowservice/v1"
	"go.temporal.io/sdk/log"
	"go.temporal.io/sdk/worker"
	"go.temporal.io/sdk/workflow"
)

// NewWorkflowReplayer creates a new instance of WorkflowReplayer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWorkflowReplayer(t interface {
	mock.TestingT
	Cleanup(func())
}) *WorkflowReplayer {
	mock := &WorkflowReplayer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// WorkflowReplayer is an autogenerated mock type for the WorkflowReplayer type
type WorkflowReplayer struct {
	mock.Mock
}

type WorkflowReplayer_Expecter struct {
	mock *mock.Mock
}

func (_m *WorkflowReplayer) EXPECT() *WorkflowReplayer_Expecter {
	return &WorkflowReplayer_Expecter{mock: &_m.Mock}
}

// RegisterDynamicWorkflow provides a mock function for the type WorkflowReplayer
func (_mock *WorkflowReplayer) RegisterDynamicWorkflow(w interface{}, options workflow.DynamicRegisterOptions) {
	_mock.Called(w, options)
	return
}

// WorkflowReplayer_RegisterDynamicWorkflow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterDynamicWorkflow'
type WorkflowReplayer_RegisterDynamicWorkflow_Call struct {
	*mock.Call
}

// RegisterDynamicWorkflow is a helper method to define mock.On call
//   - w interface{}
//   - options workflow.DynamicRegisterOptions
func (_e *WorkflowReplayer_Expecter) RegisterDynamicWorkflow(w interface{}, options interface{}) *WorkflowReplayer_RegisterDynamicWorkflow_Call {
	return &WorkflowReplayer_RegisterDynamicWorkflow_Call{Call: _e.mock.On("RegisterDynamicWorkflow", w, options)}
}

func (_c *WorkflowReplayer_RegisterDynamicWorkflow_Call) Run(run func(w interface{}, options workflow.DynamicRegisterOptions)) *WorkflowReplayer_RegisterDynamicWorkflow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 interface{}
		if args[0] != nil {
			arg0 = args[0].(interface{})
		}
		var arg1 workflow.DynamicRegisterOptions
		if args[1] != nil {
			arg1 = args[1].(workflow.DynamicRegisterOptions)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *WorkflowReplayer_RegisterDynamicWorkflow_Call) Return() *WorkflowReplayer_RegisterDynamicWorkflow_Call {
	_c.Call.Return()
	return _c
}

func (_c *WorkflowReplayer_RegisterDynamicWorkflow_Call) RunAndReturn(run func(w interface{}, options workflow.DynamicRegisterOptions)) *WorkflowReplayer_RegisterDynamicWorkflow_Call {
	_c.Run(run)
	return _c
}

// RegisterWorkflow provides a mock function for the type WorkflowReplayer
func (_mock *WorkflowReplayer) RegisterWorkflow(w interface{}) {
	_mock.Called(w)
	return
}

// WorkflowReplayer_RegisterWorkflow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterWorkflow'
type WorkflowReplayer_RegisterWorkflow_Call struct {
	*mock.Call
}

// RegisterWorkflow is a helper method to define mock.On call
//   - w interface{}
func (_e *WorkflowReplayer_Expecter) RegisterWorkflow(w interface{}) *WorkflowReplayer_RegisterWorkflow_Call {
	return &WorkflowReplayer_RegisterWorkflow_Call{Call: _e.mock.On("RegisterWorkflow", w)}
}

func (_c *WorkflowReplayer_RegisterWorkflow_Call) Run(run func(w interface{})) *WorkflowReplayer_RegisterWorkflow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 interface{}
		if args[0] != nil {
			arg0 = args[0].(interface{})
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *WorkflowReplayer_RegisterWorkflow_Call) Return() *WorkflowReplayer_RegisterWorkflow_Call {
	_c.Call.Return()
	return _c
}

func (_c *WorkflowReplayer_RegisterWorkflow_Call) RunAndReturn(run func(w interface{})) *WorkflowReplayer_RegisterWorkflow_Call {
	_c.Run(run)
	return _c
}

// RegisterWorkflowWithOptions provides a mock function for the type WorkflowReplayer
func (_mock *WorkflowReplayer) RegisterWorkflowWithOptions(w interface{}, options workflow.RegisterOptions) {
	_mock.Called(w, options)
	return
}

// WorkflowReplayer_RegisterWorkflowWithOptions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterWorkflowWithOptions'
type WorkflowReplayer_RegisterWorkflowWithOptions_Call struct {
	*mock.Call
}

// RegisterWorkflowWithOptions is a helper method to define mock.On call
//   - w interface{}
//   - options workflow.RegisterOptions
func (_e *WorkflowReplayer_Expecter) RegisterWorkflowWithOptions(w interface{}, options interface{}) *WorkflowReplayer_RegisterWorkflowWithOptions_Call {
	return &WorkflowReplayer_RegisterWorkflowWithOptions_Call{Call: _e.mock.On("RegisterWorkflowWithOptions", w, options)}
}

func (_c *WorkflowReplayer_RegisterWorkflowWithOptions_Call) Run(run func(w interface{}, options workflow.RegisterOptions)) *WorkflowReplayer_RegisterWorkflowWithOptions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 interface{}
		if args[0] != nil {
			arg0 = args[0].(interface{})
		}
		var arg1 workflow.RegisterOptions
		if args[1] != nil {
			arg1 = args[1].(workflow.RegisterOptions)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *WorkflowReplayer_RegisterWorkflowWithOptions_Call) Return() *WorkflowReplayer_RegisterWorkflowWithOptions_Call {
	_c.Call.Return()
	return _c
}

func (_c *WorkflowReplayer_RegisterWorkflowWithOptions_Call) RunAndReturn(run func(w interface{}, options workflow.RegisterOptions)) *WorkflowReplayer_RegisterWorkflowWithOptions_Call {
	_c.Run(run)
	return _c
}

// ReplayPartialWorkflowHistoryFromJSONFile provides a mock function for the type WorkflowReplayer
func (_mock *WorkflowReplayer) ReplayPartialWorkflowHistoryFromJSONFile(logger log.Logger, jsonfileName string, lastEventID int64) error {
	ret := _mock.Called(logger, jsonfileName, lastEventID)

	if len(ret) == 0 {
		panic("no return value specified for ReplayPartialWorkflowHistoryFromJSONFile")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(log.Logger, string, int64) error); ok {
		r0 = returnFunc(logger, jsonfileName, lastEventID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// WorkflowReplayer_ReplayPartialWorkflowHistoryFromJSONFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReplayPartialWorkflowHistoryFromJSONFile'
type WorkflowReplayer_ReplayPartialWorkflowHistoryFromJSONFile_Call struct {
	*mock.Call
}

// ReplayPartialWorkflowHistoryFromJSONFile is a helper method to define mock.On call
//   - logger log.Logger
//   - jsonfileName string
//   - lastEventID int64
func (_e *WorkflowReplayer_Expecter) ReplayPartialWorkflowHistoryFromJSONFile(logger interface{}, jsonfileName interface{}, lastEventID interface{}) *WorkflowReplayer_ReplayPartialWorkflowHistoryFromJSONFile_Call {
	return &WorkflowReplayer_ReplayPartialWorkflowHistoryFromJSONFile_Call{Call: _e.mock.On("ReplayPartialWorkflowHistoryFromJSONFile", logger, jsonfileName, lastEventID)}
}

func (_c *WorkflowReplayer_ReplayPartialWorkflowHistoryFromJSONFile_Call) Run(run func(logger log.Logger, jsonfileName string, lastEventID int64)) *WorkflowReplayer_ReplayPartialWorkflowHistoryFromJSONFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 log.Logger
		if args[0] != nil {
			arg0 = args[0].(log.Logger)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *WorkflowReplayer_ReplayPartialWorkflowHistoryFromJSONFile_Call) Return(err error) *WorkflowReplayer_ReplayPartialWorkflowHistoryFromJSONFile_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *WorkflowReplayer_ReplayPartialWorkflowHistoryFromJSONFile_Call) RunAndReturn(run func(logger log.Logger, jsonfileName string, lastEventID int64) error) *WorkflowReplayer_ReplayPartialWorkflowHistoryFromJSONFile_Call {
	_c.Call.Return(run)
	return _c
}

// ReplayWorkflowExecution provides a mock function for the type WorkflowReplayer
func (_mock *WorkflowReplayer) ReplayWorkflowExecution(ctx context.Context, service workflowservice.WorkflowServiceClient, logger log.Logger, namespace string, execution workflow.Execution) error {
	ret := _mock.Called(ctx, service, logger, namespace, execution)

	if len(ret) == 0 {
		panic("no return value specified for ReplayWorkflowExecution")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, workflowservice.WorkflowServiceClient, log.Logger, string, workflow.Execution) error); ok {
		r0 = returnFunc(ctx, service, logger, namespace, execution)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// WorkflowReplayer_ReplayWorkflowExecution_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReplayWorkflowExecution'
type WorkflowReplayer_ReplayWorkflowExecution_Call struct {
	*mock.Call
}

// ReplayWorkflowExecution is a helper method to define mock.On call
//   - ctx context.Context
//   - service workflowservice.WorkflowServiceClient
//   - logger log.Logger
//   - namespace string
//   - execution workflow.Execution
func (_e *WorkflowReplayer_Expecter) ReplayWorkflowExecution(ctx interface{}, service interface{}, logger interface{}, namespace interface{}, execution interface{}) *WorkflowReplayer_ReplayWorkflowExecution_Call {
	return &WorkflowReplayer_ReplayWorkflowExecution_Call{Call: _e.mock.On("ReplayWorkflowExecution", ctx, service, logger, namespace, execution)}
}

func (_c *WorkflowReplayer_ReplayWorkflowExecution_Call) Run(run func(ctx context.Context, service workflowservice.WorkflowServiceClient, logger log.Logger, namespace string, execution workflow.Execution)) *WorkflowReplayer_ReplayWorkflowExecution_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 workflowservice.WorkflowServiceClient
		if args[1] != nil {
			arg1 = args[1].(workflowservice.WorkflowServiceClient)
		}
		var arg2 log.Logger
		if args[2] != nil {
			arg2 = args[2].(log.Logger)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 workflow.Execution
		if args[4] != nil {
			arg4 = args[4].(workflow.Execution)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *WorkflowReplayer_ReplayWorkflowExecution_Call) Return(err error) *WorkflowReplayer_ReplayWorkflowExecution_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *WorkflowReplayer_ReplayWorkflowExecution_Call) RunAndReturn(run func(ctx context.Context, service workflowservice.WorkflowServiceClient, logger log.Logger, namespace string, execution workflow.Execution) error) *WorkflowReplayer_ReplayWorkflowExecution_Call {
	_c.Call.Return(run)
	return _c
}

// ReplayWorkflowHistory provides a mock function for the type WorkflowReplayer
func (_mock *WorkflowReplayer) ReplayWorkflowHistory(logger log.Logger, history1 *history.History) error {
	ret := _mock.Called(logger, history1)

	if len(ret) == 0 {
		panic("no return value specified for ReplayWorkflowHistory")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(log.Logger, *history.History) error); ok {
		r0 = returnFunc(logger, history1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// WorkflowReplayer_ReplayWorkflowHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReplayWorkflowHistory'
type WorkflowReplayer_ReplayWorkflowHistory_Call struct {
	*mock.Call
}

// ReplayWorkflowHistory is a helper method to define mock.On call
//   - logger log.Logger
//   - history1 *history.History
func (_e *WorkflowReplayer_Expecter) ReplayWorkflowHistory(logger interface{}, history1 interface{}) *WorkflowReplayer_ReplayWorkflowHistory_Call {
	return &WorkflowReplayer_ReplayWorkflowHistory_Call{Call: _e.mock.On("ReplayWorkflowHistory", logger, history1)}
}

func (_c *WorkflowReplayer_ReplayWorkflowHistory_Call) Run(run func(logger log.Logger, history1 *history.History)) *WorkflowReplayer_ReplayWorkflowHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 log.Logger
		if args[0] != nil {
			arg0 = args[0].(log.Logger)
		}
		var arg1 *history.History
		if args[1] != nil {
			arg1 = args[1].(*history.History)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *WorkflowReplayer_ReplayWorkflowHistory_Call) Return(err error) *WorkflowReplayer_ReplayWorkflowHistory_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *WorkflowReplayer_ReplayWorkflowHistory_Call) RunAndReturn(run func(logger log.Logger, history1 *history.History) error) *WorkflowReplayer_ReplayWorkflowHistory_Call {
	_c.Call.Return(run)
	return _c
}

// ReplayWorkflowHistoryFromJSONFile provides a mock function for the type WorkflowReplayer
func (_mock *WorkflowReplayer) ReplayWorkflowHistoryFromJSONFile(logger log.Logger, jsonfileName string) error {
	ret := _mock.Called(logger, jsonfileName)

	if len(ret) == 0 {
		panic("no return value specified for ReplayWorkflowHistoryFromJSONFile")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(log.Logger, string) error); ok {
		r0 = returnFunc(logger, jsonfileName)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// WorkflowReplayer_ReplayWorkflowHistoryFromJSONFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReplayWorkflowHistoryFromJSONFile'
type WorkflowReplayer_ReplayWorkflowHistoryFromJSONFile_Call struct {
	*mock.Call
}

// ReplayWorkflowHistoryFromJSONFile is a helper method to define mock.On call
//   - logger log.Logger
//   - jsonfileName string
func (_e *WorkflowReplayer_Expecter) ReplayWorkflowHistoryFromJSONFile(logger interface{}, jsonfileName interface{}) *WorkflowReplayer_ReplayWorkflowHistoryFromJSONFile_Call {
	return &WorkflowReplayer_ReplayWorkflowHistoryFromJSONFile_Call{Call: _e.mock.On("ReplayWorkflowHistoryFromJSONFile", logger, jsonfileName)}
}

func (_c *WorkflowReplayer_ReplayWorkflowHistoryFromJSONFile_Call) Run(run func(logger log.Logger, jsonfileName string)) *WorkflowReplayer_ReplayWorkflowHistoryFromJSONFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 log.Logger
		if args[0] != nil {
			arg0 = args[0].(log.Logger)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *WorkflowReplayer_ReplayWorkflowHistoryFromJSONFile_Call) Return(err error) *WorkflowReplayer_ReplayWorkflowHistoryFromJSONFile_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *WorkflowReplayer_ReplayWorkflowHistoryFromJSONFile_Call) RunAndReturn(run func(logger log.Logger, jsonfileName string) error) *WorkflowReplayer_ReplayWorkflowHistoryFromJSONFile_Call {
	_c.Call.Return(run)
	return _c
}

// ReplayWorkflowHistoryWithOptions provides a mock function for the type WorkflowReplayer
func (_mock *WorkflowReplayer) ReplayWorkflowHistoryWithOptions(logger log.Logger, history1 *history.History, options worker.ReplayWorkflowHistoryOptions) error {
	ret := _mock.Called(logger, history1, options)

	if len(ret) == 0 {
		panic("no return value specified for ReplayWorkflowHistoryWithOptions")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(log.Logger, *history.History, worker.ReplayWorkflowHistoryOptions) error); ok {
		r0 = returnFunc(logger, history1, options)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// WorkflowReplayer_ReplayWorkflowHistoryWithOptions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReplayWorkflowHistoryWithOptions'
type WorkflowReplayer_ReplayWorkflowHistoryWithOptions_Call struct {
	*mock.Call
}

// ReplayWorkflowHistoryWithOptions is a helper method to define mock.On call
//   - logger log.Logger
//   - history1 *history.History
//   - options worker.ReplayWorkflowHistoryOptions
func (_e *WorkflowReplayer_Expecter) ReplayWorkflowHistoryWithOptions(logger interface{}, history1 interface{}, options interface{}) *WorkflowReplayer_ReplayWorkflowHistoryWithOptions_Call {
	return &WorkflowReplayer_ReplayWorkflowHistoryWithOptions_Call{Call: _e.mock.On("ReplayWorkflowHistoryWithOptions", logger, history1, options)}
}

func (_c *WorkflowReplayer_ReplayWorkflowHistoryWithOptions_Call) Run(run func(logger log.Logger, history1 *history.History, options worker.ReplayWorkflowHistoryOptions)) *WorkflowReplayer_ReplayWorkflowHistoryWithOptions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 log.Logger
		if args[0] != nil {
			arg0 = args[0].(log.Logger)
		}
		var arg1 *history.History
		if args[1] != nil {
			arg1 = args[1].(*history.History)
		}
		var arg2 worker.ReplayWorkflowHistoryOptions
		if args[2] != nil {
			arg2 = args[2].(worker.ReplayWorkflowHistoryOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *WorkflowReplayer_ReplayWorkflowHistoryWithOptions_Call) Return(err error) *WorkflowReplayer_ReplayWorkflowHistoryWithOptions_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *WorkflowReplayer_ReplayWorkflowHistoryWithOptions_Call) RunAndReturn(run func(logger log.Logger, history1 *history.History, options worker.ReplayWorkflowHistoryOptions) error) *WorkflowReplayer_ReplayWorkflowHistoryWithOptions_Call {
	_c.Call.Return(run)
	return _c
}
