// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewWorkflowUpdateHandle creates a new instance of WorkflowUpdateHandle. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWorkflowUpdateHandle(t interface {
	mock.TestingT
	Cleanup(func())
}) *WorkflowUpdateHandle {
	mock := &WorkflowUpdateHandle{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// WorkflowUpdateHandle is an autogenerated mock type for the WorkflowUpdateHandle type
type WorkflowUpdateHandle struct {
	mock.Mock
}

type WorkflowUpdateHandle_Expecter struct {
	mock *mock.Mock
}

func (_m *WorkflowUpdateHandle) EXPECT() *WorkflowUpdateHandle_Expecter {
	return &WorkflowUpdateHandle_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type WorkflowUpdateHandle
func (_mock *WorkflowUpdateHandle) Get(ctx context.Context, valuePtr interface{}) error {
	ret := _mock.Called(ctx, valuePtr)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, interface{}) error); ok {
		r0 = returnFunc(ctx, valuePtr)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// WorkflowUpdateHandle_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type WorkflowUpdateHandle_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - valuePtr interface{}
func (_e *WorkflowUpdateHandle_Expecter) Get(ctx interface{}, valuePtr interface{}) *WorkflowUpdateHandle_Get_Call {
	return &WorkflowUpdateHandle_Get_Call{Call: _e.mock.On("Get", ctx, valuePtr)}
}

func (_c *WorkflowUpdateHandle_Get_Call) Run(run func(ctx context.Context, valuePtr interface{})) *WorkflowUpdateHandle_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 interface{}
		if args[1] != nil {
			arg1 = args[1].(interface{})
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *WorkflowUpdateHandle_Get_Call) Return(err error) *WorkflowUpdateHandle_Get_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *WorkflowUpdateHandle_Get_Call) RunAndReturn(run func(ctx context.Context, valuePtr interface{}) error) *WorkflowUpdateHandle_Get_Call {
	_c.Call.Return(run)
	return _c
}

// RunID provides a mock function for the type WorkflowUpdateHandle
func (_mock *WorkflowUpdateHandle) RunID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for RunID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// WorkflowUpdateHandle_RunID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RunID'
type WorkflowUpdateHandle_RunID_Call struct {
	*mock.Call
}

// RunID is a helper method to define mock.On call
func (_e *WorkflowUpdateHandle_Expecter) RunID() *WorkflowUpdateHandle_RunID_Call {
	return &WorkflowUpdateHandle_RunID_Call{Call: _e.mock.On("RunID")}
}

func (_c *WorkflowUpdateHandle_RunID_Call) Run(run func()) *WorkflowUpdateHandle_RunID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *WorkflowUpdateHandle_RunID_Call) Return(s string) *WorkflowUpdateHandle_RunID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *WorkflowUpdateHandle_RunID_Call) RunAndReturn(run func() string) *WorkflowUpdateHandle_RunID_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateID provides a mock function for the type WorkflowUpdateHandle
func (_mock *WorkflowUpdateHandle) UpdateID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for UpdateID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// WorkflowUpdateHandle_UpdateID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateID'
type WorkflowUpdateHandle_UpdateID_Call struct {
	*mock.Call
}

// UpdateID is a helper method to define mock.On call
func (_e *WorkflowUpdateHandle_Expecter) UpdateID() *WorkflowUpdateHandle_UpdateID_Call {
	return &WorkflowUpdateHandle_UpdateID_Call{Call: _e.mock.On("UpdateID")}
}

func (_c *WorkflowUpdateHandle_UpdateID_Call) Run(run func()) *WorkflowUpdateHandle_UpdateID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *WorkflowUpdateHandle_UpdateID_Call) Return(s string) *WorkflowUpdateHandle_UpdateID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *WorkflowUpdateHandle_UpdateID_Call) RunAndReturn(run func() string) *WorkflowUpdateHandle_UpdateID_Call {
	_c.Call.Return(run)
	return _c
}

// WorkflowID provides a mock function for the type WorkflowUpdateHandle
func (_mock *WorkflowUpdateHandle) WorkflowID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for WorkflowID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// WorkflowUpdateHandle_WorkflowID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WorkflowID'
type WorkflowUpdateHandle_WorkflowID_Call struct {
	*mock.Call
}

// WorkflowID is a helper method to define mock.On call
func (_e *WorkflowUpdateHandle_Expecter) WorkflowID() *WorkflowUpdateHandle_WorkflowID_Call {
	return &WorkflowUpdateHandle_WorkflowID_Call{Call: _e.mock.On("WorkflowID")}
}

func (_c *WorkflowUpdateHandle_WorkflowID_Call) Run(run func()) *WorkflowUpdateHandle_WorkflowID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *WorkflowUpdateHandle_WorkflowID_Call) Return(s string) *WorkflowUpdateHandle_WorkflowID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *WorkflowUpdateHandle_WorkflowID_Call) RunAndReturn(run func() string) *WorkflowUpdateHandle_WorkflowID_Call {
	_c.Call.Return(run)
	return _c
}
