// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"go.temporal.io/sdk/internal"
)

// NewWorkerDeploymentHandle creates a new instance of WorkerDeploymentHandle. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWorkerDeploymentHandle(t interface {
	mock.TestingT
	Cleanup(func())
}) *WorkerDeploymentHandle {
	mock := &WorkerDeploymentHandle{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// WorkerDeploymentHandle is an autogenerated mock type for the WorkerDeploymentHandle type
type WorkerDeploymentHandle struct {
	mock.Mock
}

type WorkerDeploymentHandle_Expecter struct {
	mock *mock.Mock
}

func (_m *WorkerDeploymentHandle) EXPECT() *WorkerDeploymentHandle_Expecter {
	return &WorkerDeploymentHandle_Expecter{mock: &_m.Mock}
}

// DeleteVersion provides a mock function for the type WorkerDeploymentHandle
func (_mock *WorkerDeploymentHandle) DeleteVersion(ctx context.Context, options internal.WorkerDeploymentDeleteVersionOptions) (internal.WorkerDeploymentDeleteVersionResponse, error) {
	ret := _mock.Called(ctx, options)

	if len(ret) == 0 {
		panic("no return value specified for DeleteVersion")
	}

	var r0 internal.WorkerDeploymentDeleteVersionResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, internal.WorkerDeploymentDeleteVersionOptions) (internal.WorkerDeploymentDeleteVersionResponse, error)); ok {
		return returnFunc(ctx, options)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, internal.WorkerDeploymentDeleteVersionOptions) internal.WorkerDeploymentDeleteVersionResponse); ok {
		r0 = returnFunc(ctx, options)
	} else {
		r0 = ret.Get(0).(internal.WorkerDeploymentDeleteVersionResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, internal.WorkerDeploymentDeleteVersionOptions) error); ok {
		r1 = returnFunc(ctx, options)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// WorkerDeploymentHandle_DeleteVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteVersion'
type WorkerDeploymentHandle_DeleteVersion_Call struct {
	*mock.Call
}

// DeleteVersion is a helper method to define mock.On call
//   - ctx context.Context
//   - options internal.WorkerDeploymentDeleteVersionOptions
func (_e *WorkerDeploymentHandle_Expecter) DeleteVersion(ctx interface{}, options interface{}) *WorkerDeploymentHandle_DeleteVersion_Call {
	return &WorkerDeploymentHandle_DeleteVersion_Call{Call: _e.mock.On("DeleteVersion", ctx, options)}
}

func (_c *WorkerDeploymentHandle_DeleteVersion_Call) Run(run func(ctx context.Context, options internal.WorkerDeploymentDeleteVersionOptions)) *WorkerDeploymentHandle_DeleteVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 internal.WorkerDeploymentDeleteVersionOptions
		if args[1] != nil {
			arg1 = args[1].(internal.WorkerDeploymentDeleteVersionOptions)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *WorkerDeploymentHandle_DeleteVersion_Call) Return(workerDeploymentDeleteVersionResponse internal.WorkerDeploymentDeleteVersionResponse, err error) *WorkerDeploymentHandle_DeleteVersion_Call {
	_c.Call.Return(workerDeploymentDeleteVersionResponse, err)
	return _c
}

func (_c *WorkerDeploymentHandle_DeleteVersion_Call) RunAndReturn(run func(ctx context.Context, options internal.WorkerDeploymentDeleteVersionOptions) (internal.WorkerDeploymentDeleteVersionResponse, error)) *WorkerDeploymentHandle_DeleteVersion_Call {
	_c.Call.Return(run)
	return _c
}

// Describe provides a mock function for the type WorkerDeploymentHandle
func (_mock *WorkerDeploymentHandle) Describe(ctx context.Context, options internal.WorkerDeploymentDescribeOptions) (internal.WorkerDeploymentDescribeResponse, error) {
	ret := _mock.Called(ctx, options)

	if len(ret) == 0 {
		panic("no return value specified for Describe")
	}

	var r0 internal.WorkerDeploymentDescribeResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, internal.WorkerDeploymentDescribeOptions) (internal.WorkerDeploymentDescribeResponse, error)); ok {
		return returnFunc(ctx, options)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, internal.WorkerDeploymentDescribeOptions) internal.WorkerDeploymentDescribeResponse); ok {
		r0 = returnFunc(ctx, options)
	} else {
		r0 = ret.Get(0).(internal.WorkerDeploymentDescribeResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, internal.WorkerDeploymentDescribeOptions) error); ok {
		r1 = returnFunc(ctx, options)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// WorkerDeploymentHandle_Describe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Describe'
type WorkerDeploymentHandle_Describe_Call struct {
	*mock.Call
}

// Describe is a helper method to define mock.On call
//   - ctx context.Context
//   - options internal.WorkerDeploymentDescribeOptions
func (_e *WorkerDeploymentHandle_Expecter) Describe(ctx interface{}, options interface{}) *WorkerDeploymentHandle_Describe_Call {
	return &WorkerDeploymentHandle_Describe_Call{Call: _e.mock.On("Describe", ctx, options)}
}

func (_c *WorkerDeploymentHandle_Describe_Call) Run(run func(ctx context.Context, options internal.WorkerDeploymentDescribeOptions)) *WorkerDeploymentHandle_Describe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 internal.WorkerDeploymentDescribeOptions
		if args[1] != nil {
			arg1 = args[1].(internal.WorkerDeploymentDescribeOptions)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *WorkerDeploymentHandle_Describe_Call) Return(workerDeploymentDescribeResponse internal.WorkerDeploymentDescribeResponse, err error) *WorkerDeploymentHandle_Describe_Call {
	_c.Call.Return(workerDeploymentDescribeResponse, err)
	return _c
}

func (_c *WorkerDeploymentHandle_Describe_Call) RunAndReturn(run func(ctx context.Context, options internal.WorkerDeploymentDescribeOptions) (internal.WorkerDeploymentDescribeResponse, error)) *WorkerDeploymentHandle_Describe_Call {
	_c.Call.Return(run)
	return _c
}

// DescribeVersion provides a mock function for the type WorkerDeploymentHandle
func (_mock *WorkerDeploymentHandle) DescribeVersion(ctx context.Context, options internal.WorkerDeploymentDescribeVersionOptions) (internal.WorkerDeploymentVersionDescription, error) {
	ret := _mock.Called(ctx, options)

	if len(ret) == 0 {
		panic("no return value specified for DescribeVersion")
	}

	var r0 internal.WorkerDeploymentVersionDescription
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, internal.WorkerDeploymentDescribeVersionOptions) (internal.WorkerDeploymentVersionDescription, error)); ok {
		return returnFunc(ctx, options)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, internal.WorkerDeploymentDescribeVersionOptions) internal.WorkerDeploymentVersionDescription); ok {
		r0 = returnFunc(ctx, options)
	} else {
		r0 = ret.Get(0).(internal.WorkerDeploymentVersionDescription)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, internal.WorkerDeploymentDescribeVersionOptions) error); ok {
		r1 = returnFunc(ctx, options)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// WorkerDeploymentHandle_DescribeVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DescribeVersion'
type WorkerDeploymentHandle_DescribeVersion_Call struct {
	*mock.Call
}

// DescribeVersion is a helper method to define mock.On call
//   - ctx context.Context
//   - options internal.WorkerDeploymentDescribeVersionOptions
func (_e *WorkerDeploymentHandle_Expecter) DescribeVersion(ctx interface{}, options interface{}) *WorkerDeploymentHandle_DescribeVersion_Call {
	return &WorkerDeploymentHandle_DescribeVersion_Call{Call: _e.mock.On("DescribeVersion", ctx, options)}
}

func (_c *WorkerDeploymentHandle_DescribeVersion_Call) Run(run func(ctx context.Context, options internal.WorkerDeploymentDescribeVersionOptions)) *WorkerDeploymentHandle_DescribeVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 internal.WorkerDeploymentDescribeVersionOptions
		if args[1] != nil {
			arg1 = args[1].(internal.WorkerDeploymentDescribeVersionOptions)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *WorkerDeploymentHandle_DescribeVersion_Call) Return(workerDeploymentVersionDescription internal.WorkerDeploymentVersionDescription, err error) *WorkerDeploymentHandle_DescribeVersion_Call {
	_c.Call.Return(workerDeploymentVersionDescription, err)
	return _c
}

func (_c *WorkerDeploymentHandle_DescribeVersion_Call) RunAndReturn(run func(ctx context.Context, options internal.WorkerDeploymentDescribeVersionOptions) (internal.WorkerDeploymentVersionDescription, error)) *WorkerDeploymentHandle_DescribeVersion_Call {
	_c.Call.Return(run)
	return _c
}

// SetCurrentVersion provides a mock function for the type WorkerDeploymentHandle
func (_mock *WorkerDeploymentHandle) SetCurrentVersion(ctx context.Context, options internal.WorkerDeploymentSetCurrentVersionOptions) (internal.WorkerDeploymentSetCurrentVersionResponse, error) {
	ret := _mock.Called(ctx, options)

	if len(ret) == 0 {
		panic("no return value specified for SetCurrentVersion")
	}

	var r0 internal.WorkerDeploymentSetCurrentVersionResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, internal.WorkerDeploymentSetCurrentVersionOptions) (internal.WorkerDeploymentSetCurrentVersionResponse, error)); ok {
		return returnFunc(ctx, options)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, internal.WorkerDeploymentSetCurrentVersionOptions) internal.WorkerDeploymentSetCurrentVersionResponse); ok {
		r0 = returnFunc(ctx, options)
	} else {
		r0 = ret.Get(0).(internal.WorkerDeploymentSetCurrentVersionResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, internal.WorkerDeploymentSetCurrentVersionOptions) error); ok {
		r1 = returnFunc(ctx, options)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// WorkerDeploymentHandle_SetCurrentVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetCurrentVersion'
type WorkerDeploymentHandle_SetCurrentVersion_Call struct {
	*mock.Call
}

// SetCurrentVersion is a helper method to define mock.On call
//   - ctx context.Context
//   - options internal.WorkerDeploymentSetCurrentVersionOptions
func (_e *WorkerDeploymentHandle_Expecter) SetCurrentVersion(ctx interface{}, options interface{}) *WorkerDeploymentHandle_SetCurrentVersion_Call {
	return &WorkerDeploymentHandle_SetCurrentVersion_Call{Call: _e.mock.On("SetCurrentVersion", ctx, options)}
}

func (_c *WorkerDeploymentHandle_SetCurrentVersion_Call) Run(run func(ctx context.Context, options internal.WorkerDeploymentSetCurrentVersionOptions)) *WorkerDeploymentHandle_SetCurrentVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 internal.WorkerDeploymentSetCurrentVersionOptions
		if args[1] != nil {
			arg1 = args[1].(internal.WorkerDeploymentSetCurrentVersionOptions)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *WorkerDeploymentHandle_SetCurrentVersion_Call) Return(workerDeploymentSetCurrentVersionResponse internal.WorkerDeploymentSetCurrentVersionResponse, err error) *WorkerDeploymentHandle_SetCurrentVersion_Call {
	_c.Call.Return(workerDeploymentSetCurrentVersionResponse, err)
	return _c
}

func (_c *WorkerDeploymentHandle_SetCurrentVersion_Call) RunAndReturn(run func(ctx context.Context, options internal.WorkerDeploymentSetCurrentVersionOptions) (internal.WorkerDeploymentSetCurrentVersionResponse, error)) *WorkerDeploymentHandle_SetCurrentVersion_Call {
	_c.Call.Return(run)
	return _c
}

// SetManagerIdentity provides a mock function for the type WorkerDeploymentHandle
func (_mock *WorkerDeploymentHandle) SetManagerIdentity(ctx context.Context, options internal.WorkerDeploymentSetManagerIdentityOptions) (internal.WorkerDeploymentSetManagerIdentityResponse, error) {
	ret := _mock.Called(ctx, options)

	if len(ret) == 0 {
		panic("no return value specified for SetManagerIdentity")
	}

	var r0 internal.WorkerDeploymentSetManagerIdentityResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, internal.WorkerDeploymentSetManagerIdentityOptions) (internal.WorkerDeploymentSetManagerIdentityResponse, error)); ok {
		return returnFunc(ctx, options)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, internal.WorkerDeploymentSetManagerIdentityOptions) internal.WorkerDeploymentSetManagerIdentityResponse); ok {
		r0 = returnFunc(ctx, options)
	} else {
		r0 = ret.Get(0).(internal.WorkerDeploymentSetManagerIdentityResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, internal.WorkerDeploymentSetManagerIdentityOptions) error); ok {
		r1 = returnFunc(ctx, options)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// WorkerDeploymentHandle_SetManagerIdentity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetManagerIdentity'
type WorkerDeploymentHandle_SetManagerIdentity_Call struct {
	*mock.Call
}

// SetManagerIdentity is a helper method to define mock.On call
//   - ctx context.Context
//   - options internal.WorkerDeploymentSetManagerIdentityOptions
func (_e *WorkerDeploymentHandle_Expecter) SetManagerIdentity(ctx interface{}, options interface{}) *WorkerDeploymentHandle_SetManagerIdentity_Call {
	return &WorkerDeploymentHandle_SetManagerIdentity_Call{Call: _e.mock.On("SetManagerIdentity", ctx, options)}
}

func (_c *WorkerDeploymentHandle_SetManagerIdentity_Call) Run(run func(ctx context.Context, options internal.WorkerDeploymentSetManagerIdentityOptions)) *WorkerDeploymentHandle_SetManagerIdentity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 internal.WorkerDeploymentSetManagerIdentityOptions
		if args[1] != nil {
			arg1 = args[1].(internal.WorkerDeploymentSetManagerIdentityOptions)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *WorkerDeploymentHandle_SetManagerIdentity_Call) Return(workerDeploymentSetManagerIdentityResponse internal.WorkerDeploymentSetManagerIdentityResponse, err error) *WorkerDeploymentHandle_SetManagerIdentity_Call {
	_c.Call.Return(workerDeploymentSetManagerIdentityResponse, err)
	return _c
}

func (_c *WorkerDeploymentHandle_SetManagerIdentity_Call) RunAndReturn(run func(ctx context.Context, options internal.WorkerDeploymentSetManagerIdentityOptions) (internal.WorkerDeploymentSetManagerIdentityResponse, error)) *WorkerDeploymentHandle_SetManagerIdentity_Call {
	_c.Call.Return(run)
	return _c
}

// SetRampingVersion provides a mock function for the type WorkerDeploymentHandle
func (_mock *WorkerDeploymentHandle) SetRampingVersion(ctx context.Context, options internal.WorkerDeploymentSetRampingVersionOptions) (internal.WorkerDeploymentSetRampingVersionResponse, error) {
	ret := _mock.Called(ctx, options)

	if len(ret) == 0 {
		panic("no return value specified for SetRampingVersion")
	}

	var r0 internal.WorkerDeploymentSetRampingVersionResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, internal.WorkerDeploymentSetRampingVersionOptions) (internal.WorkerDeploymentSetRampingVersionResponse, error)); ok {
		return returnFunc(ctx, options)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, internal.WorkerDeploymentSetRampingVersionOptions) internal.WorkerDeploymentSetRampingVersionResponse); ok {
		r0 = returnFunc(ctx, options)
	} else {
		r0 = ret.Get(0).(internal.WorkerDeploymentSetRampingVersionResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, internal.WorkerDeploymentSetRampingVersionOptions) error); ok {
		r1 = returnFunc(ctx, options)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// WorkerDeploymentHandle_SetRampingVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetRampingVersion'
type WorkerDeploymentHandle_SetRampingVersion_Call struct {
	*mock.Call
}

// SetRampingVersion is a helper method to define mock.On call
//   - ctx context.Context
//   - options internal.WorkerDeploymentSetRampingVersionOptions
func (_e *WorkerDeploymentHandle_Expecter) SetRampingVersion(ctx interface{}, options interface{}) *WorkerDeploymentHandle_SetRampingVersion_Call {
	return &WorkerDeploymentHandle_SetRampingVersion_Call{Call: _e.mock.On("SetRampingVersion", ctx, options)}
}

func (_c *WorkerDeploymentHandle_SetRampingVersion_Call) Run(run func(ctx context.Context, options internal.WorkerDeploymentSetRampingVersionOptions)) *WorkerDeploymentHandle_SetRampingVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 internal.WorkerDeploymentSetRampingVersionOptions
		if args[1] != nil {
			arg1 = args[1].(internal.WorkerDeploymentSetRampingVersionOptions)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *WorkerDeploymentHandle_SetRampingVersion_Call) Return(workerDeploymentSetRampingVersionResponse internal.WorkerDeploymentSetRampingVersionResponse, err error) *WorkerDeploymentHandle_SetRampingVersion_Call {
	_c.Call.Return(workerDeploymentSetRampingVersionResponse, err)
	return _c
}

func (_c *WorkerDeploymentHandle_SetRampingVersion_Call) RunAndReturn(run func(ctx context.Context, options internal.WorkerDeploymentSetRampingVersionOptions) (internal.WorkerDeploymentSetRampingVersionResponse, error)) *WorkerDeploymentHandle_SetRampingVersion_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateVersionMetadata provides a mock function for the type WorkerDeploymentHandle
func (_mock *WorkerDeploymentHandle) UpdateVersionMetadata(ctx context.Context, options internal.WorkerDeploymentUpdateVersionMetadataOptions) (internal.WorkerDeploymentUpdateVersionMetadataResponse, error) {
	ret := _mock.Called(ctx, options)

	if len(ret) == 0 {
		panic("no return value specified for UpdateVersionMetadata")
	}

	var r0 internal.WorkerDeploymentUpdateVersionMetadataResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, internal.WorkerDeploymentUpdateVersionMetadataOptions) (internal.WorkerDeploymentUpdateVersionMetadataResponse, error)); ok {
		return returnFunc(ctx, options)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, internal.WorkerDeploymentUpdateVersionMetadataOptions) internal.WorkerDeploymentUpdateVersionMetadataResponse); ok {
		r0 = returnFunc(ctx, options)
	} else {
		r0 = ret.Get(0).(internal.WorkerDeploymentUpdateVersionMetadataResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, internal.WorkerDeploymentUpdateVersionMetadataOptions) error); ok {
		r1 = returnFunc(ctx, options)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// WorkerDeploymentHandle_UpdateVersionMetadata_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateVersionMetadata'
type WorkerDeploymentHandle_UpdateVersionMetadata_Call struct {
	*mock.Call
}

// UpdateVersionMetadata is a helper method to define mock.On call
//   - ctx context.Context
//   - options internal.WorkerDeploymentUpdateVersionMetadataOptions
func (_e *WorkerDeploymentHandle_Expecter) UpdateVersionMetadata(ctx interface{}, options interface{}) *WorkerDeploymentHandle_UpdateVersionMetadata_Call {
	return &WorkerDeploymentHandle_UpdateVersionMetadata_Call{Call: _e.mock.On("UpdateVersionMetadata", ctx, options)}
}

func (_c *WorkerDeploymentHandle_UpdateVersionMetadata_Call) Run(run func(ctx context.Context, options internal.WorkerDeploymentUpdateVersionMetadataOptions)) *WorkerDeploymentHandle_UpdateVersionMetadata_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 internal.WorkerDeploymentUpdateVersionMetadataOptions
		if args[1] != nil {
			arg1 = args[1].(internal.WorkerDeploymentUpdateVersionMetadataOptions)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *WorkerDeploymentHandle_UpdateVersionMetadata_Call) Return(workerDeploymentUpdateVersionMetadataResponse internal.WorkerDeploymentUpdateVersionMetadataResponse, err error) *WorkerDeploymentHandle_UpdateVersionMetadata_Call {
	_c.Call.Return(workerDeploymentUpdateVersionMetadataResponse, err)
	return _c
}

func (_c *WorkerDeploymentHandle_UpdateVersionMetadata_Call) RunAndReturn(run func(ctx context.Context, options internal.WorkerDeploymentUpdateVersionMetadataOptions) (internal.WorkerDeploymentUpdateVersionMetadataResponse, error)) *WorkerDeploymentHandle_UpdateVersionMetadata_Call {
	_c.Call.Return(run)
	return _c
}
